Makefile, deploy/Dockerfile, deploy/olm-catalog/performance-addon-operators/0.0.1/performance-addon-operators.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operators/0.0.1/performance.openshift.io_cpuperformanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operators/performance-addon-operators.package.yaml
adds the following new make targets + add adds default CSV
- build-containers: builds registry and operator containers.
- push-containers: pushes dev containers to an external repo (defaults to quay)
- generate-latest-dev-csv : generates a CSV we use for dev deployments
- ci-job: executes lots of validation checks plus unit tests
=> Container building make targets

Makefile, build/Dockerfile, deploy/Dockerfile, deploy/olm-catalog/performance-addon-operators/0.0.1/performance-addon-operators.v0.0.1.clusterserviceversion.yaml, hack/clean-deploy.sh, hack/deploy.sh, openshift-ci/Dockerfile.deploy, openshift-ci/Dockerfile.registry.build
dev flow logic for testing the operator. 
```
export REGISTRY_NAMESPACE=<your quay.io namespace>
make build-containers
make push-containers
```
Make sure your images are made public in your quay.io account.
Then deploy the operator using this make target.
```
make cluster-deploy
```
There currently isn't any logic to verify the deployment. This simply posts the manifests for now.
Verify the install by checking the csv is posted.
```
$ oc get csv --all-namespaces | grep performance-addon
openshift-performance-addon            performance-addon-operators.v0.0.1   Performance Addon Operators   0.0.1                InstallReady
```
That the catalog container is online.
```
$ oc get pods --all-namespaces | grep performance
openshift-marketplace …
```
=> Operator cluster deploy make targets

build/assets/tuned/openshift-node-network-latency
force_latency parameter in tuned profile is supported only for versions greater than 2.11. 
Tuned 2.11 is the current version we are using (matching RHEL 7.7/RHCOS in ocp 4.4) 
Change for supporting cstate can be found here:
https://github.com/redhat-performance/tuned/commit/0ec40e036019c4c062d76a31d676565a09c615dd#diff-6abf9f63e8d9fbfe6bddc23b8addfa1a
=> Force latency is not supported with cstate in tuned 2.11

Makefile
To better integrate with isolated build systems, we could make use
of a target which just builds the binary, without the vet/lint/fmt
steps which we can take for granted - code not compliant should
never be committed in the first place.
=> makefile: add a target to only build the binary

pkg/apis/performance/v1alpha1/performanceprofile_types.go, pkg/controller/performanceprofile/components/profile/profile.go, pkg/controller/performanceprofile/performanceprofile_controller.go, pkg/controller/performanceprofile/performanceprofile_controller_test.go
Placing the "performance.openshift.io/pause-reconcile=true" annotation on a performance profile object will prevent the operator from reconciling on that object.
This is an escape hatch that allows someone to manually modify a configuration owned by the performance profile and not have our operator stomp on their changes.
=> Add ability to "pause" a performance profile's reconcile loop

openshift-ci/Dockerfile.registry.upstream.dev
we need this as part of the Openshift CI integration which will promote our images to quay. I registered the performance-addon-operator quay account which is what we'll sync our builds to.
=> Adds dockerfile for building and promoting upstream dev public images

Makefile, functests/performance/performance.go, functests/utils/consts.go, hack/run-functests.sh
`make functests` also setup labels and deploy the operator (see https://github.com/openshift-kni/performance-addon-operators/blob/f8ca736d9c83ef39dd1e581d855c94865a565400/Makefile#L126)
Also, the tests are pinned to the labels / profiles applied in the setup phase.
This PR makes those configurable and adds a makefile rule that only runs tests.
=> Make it possible to run tests against an external cluster

hack/label-worker-rt.sh
Some clusters could have master nodes labeled as 'worker'.
This patch only selects worker node and excludes nodes with
'master' label.
=> Exclusively select worker node

openshift-ci/Dockerfile.registry.upstream.dev
reflect the change to use the newly created openshift-kni org in quay.io.
=> point our upstream images to the openshift-kni quay.io org

openshift-ci/Dockerfile.tools
Hopefully fixes this issue in CI:
```
ERROR: gcloud failed to load: invalid syntax (yaml_command_translator.py, line 241)
gcloud_main = _import_gcloud_main()
import googlecloudsdk.gcloud_main
from googlecloudsdk.command_lib.util.apis import yaml_command_translator
if self.spec.async:
SyntaxError: invalid syntax
This usually indicates corruption in your gcloud installation or problems with your Python interpreter.
Please verify that the following is the path to a working Python 2.7 executable:
/usr/bin/python3
If it is not, please set the CLOUDSDK_PYTHON environment variable to point to a working Python 2.7 executable.
```
=> Try to make glcoud client happy with python2

build/assets/tuned/openshift-node-network-latency
Revert https://github.com/openshift-kni/performance-addon-operators/pull/31.
Performance parameter : `force_latency`  can use cstate now that https://github.com/openshift/cluster-node-tuning-operator/pull/105 is merged.
=> Revert back force_latency to use cstate

functests/utils/nodes/nodes.go
Timeout parameter of `oc rsh` parameters started to drop deprecation error, that brake
out CI tests.
=> functests: fix CI tests to pass on the latest OpenShift

Makefile
We want to to generate the manifests in isolated build systems,
but in order to do so we must have all the dependencies ready,
because we cannot fetch stuff from internet - even from trusted sources.
For this reason, we include the operator-sdk binary in the tree.
=> operator-sdk: "vendor" the executable

hack/csv-generate.sh, tools/csv-generator/csv-generator.go
This patch extends the CSV generator tooling to allow
it to be used to generate the OCP manifests seamlessly.
Few changes are needed:
- allow to inject arbitrary key/value annotations from
an external file
the changes are meant to be optional, and they are meant to
not disrupt the existing flows.
=> csvgen: extend to accomodate OCP needs

build/assets/scripts/pre-boot-tuning.sh
This is just a quick update to let taskset use the provided list of reserved CPUs, instead of calculating
a mask that can be delegated to other components soon.
Signed-off-by: Vladik Romanovsky <vromanso@redhat.com>
=> let taskset use the reserved CPUs list instead of a mask

build/assets/scripts/pre-boot-tuning.sh, build/assets/tuned/openshift-node-real-time-kernel, cluster-setup/base/performance/performance_profile.yaml, deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml, deploy/crds/performance.openshift.io_v1alpha1_performanceprofile_cr.yaml, deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml, pkg/apis/performance/v1alpha1/performanceprofile_types.go, pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go, pkg/controller/performanceprofile/components/profile/profile.go, pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/performanceprofile_controller_test.go, pkg/utils/testing/testing.go
The spec.CPU.NonIsolated option is redundant. It can be represented by the same cpu set that spec.CPU.Reserved represents now. If we find we need fine granular control over how the CPUs in the reserved set are used, we can re-approach making an addition to the API at that point. 
The spec.CPU.Isolated option needs two modes, one that just uses the tuned options for cpu partitioning, and another that includes both the tuned settings plus setting the isolcpu kernel option.
The reasoning here is that using the isolcpus kernel option is not always appropriate depending on the use case. We might want to partition a set of isolated cpus and still allow those cpus to load balance. With the addition of the spec.CPU.EnableIsolcpus boolean value, we can toggle on usage of isolcpus kernel args …
=> API Isolated and NonIsolated CPU changes

build/assets/scripts/pre-boot-tuning.sh, build/assets/tuned/openshift-node-real-time-kernel, cluster-setup/ci-cluster/performance/performance_profile.patch.yaml, functests/performance/cpu_management.go, functests/performance/performance.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go, pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/components/utils.go, pkg/controller/performanceprofile/components/utils_suite_test.go, pkg/controller/performanceprofile/components/utils_test.go
Pre boot tuning was changed to operate as following:
- Compute non_isolated_cpus_mask and its invert in the operator code
- Set kernel argument for tuned.non_isolcpus=<non isolated cpus mask> to set `/sys/devices/virtual/workqueue/cpumask` using RHCOS hooks in early boot stage
- openshift-node-real-time-kernel will set cpumask for `/sys/bus/workqueue/devices/writeback/cpumask`. (Tuned)
- Add to ignition file a custom CPUAffinity file : `/etc/systemd/system.conf.d/setAffinity.conf`
- Set systemd with the custom file:
`rpm-ostree initramfs --enable --arg=-I --arg="/etc/systemd/system.conf /etc/systemd/system.conf.d/setAffinity.conf"`
- Set irqbalance in the script (no need to set it in initramfs)
**Additional Info**
The operator takes the NON_ISOLATED_CPUS (=reserved cpus) parameter and …
=> Adjust pre boot tunings

Makefile, hack/csv-generate.sh, tools/csv-generator/csv-generator.go
Add metadata to make the CSV look a bit nicer in the operatorHUB ui.
=> csv: add more metadata

openshift-ci/Dockerfile.registry.upstream.dev
No way to detect branch when building the image, so we need to hardcode the tag for now
=> [release-4.4] Use correct operator tag in upstream registry image

deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml, deploy/role.yaml
Performance profile is cluster scope resource, so events creation should be done on the cluster level.
=> Fix events permissions

hack/deploy.sh, openshift-ci/Dockerfile.registry.build
WIP
Checking if we have the IMAGE_FORMAT env var available in the image build step now.
Otherwise maybe just updated hardcoded URL.
Or get rid of registry image like in #87
=> Updated CI image registry URL

build/assets/scripts/pre-boot-tuning.sh, build/assets/scripts/reboot.sh, functests/performance/performance.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
**What is the problem**
There are inconsistent results of rpm-ostree status after pre-boot service have run initramfs injection: `rpm-ostree initramfs --enable --arg=-I --arg="/etc/systemd/system.conf /etc/systemd/system.conf.d/setAffinity.conf" `
The expectation is that the deployment will contain these files:
`Initramfs: -I /etc/systemd/system.conf /etc/systemd/system.conf.d/setAffinity.conf `  (can be viewed by running `rpm-ostree status -b` after a successful deployment)
Its seems that the reason for that might be connected to out-of-sync issues or race conditions.
**What was fixed**
- Pre boot script was changed to initiate a reboot directly from rpm-ostree (using -r flag) to try and be in sync.
- Reboot service was removed since it is not needed anymore (reboot is done in pre-boot …
=> Reboot from rpm-ostree injection in pre-boot

openshift-ci/Dockerfile.registry.build, openshift-ci/Dockerfile.registry.intermediate, openshift-ci/Dockerfile.registry.upstream.dev
`master` branch is for OCP version 4.5, so let's use the correct registry base image.
=> Pin registry image to version 4.5

pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go
MCO has schema validation now and expects TyeMeta to be filled on embedded k8s KubeletConfiguration resource
=> Fixed KubeletConfig

cluster-setup/ci-cluster/performance/performance_profile.patch.yaml, deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml, deploy/crds/performance.openshift.io_v1alpha1_performanceprofile_cr.yaml, deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml, functests/performance/performance.go, pkg/apis/performance/v1alpha1/performanceprofile_types.go, pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
- Added an additional field to the performance profile CRD: `additionalKernelArgs` which is optional and can contain a string list of additional kernel argument that are not included as base arguments.
This gives the field engineer the capability to add more kargs (idle=poll and etc) via the performance_profile.yaml when they deem it necessary.
- Set the following kargs as base 
`intel_iommu=on iommu=pt default_hugepagesz=1GB hugepagesz=1G hugepages=32 intel_pstate=disable skew_tick=1 nohz=on nohz_full=<isolated list> rcu_nocbs=<isolated list> tuned.non_isolcpus=<reserved mask> nosoftlockup`
=> Add additional kerenel arguments option in CRD

cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
Reverts openshift-kni/performance-addon-operators#134
The 4.5 rehearsal on https://github.com/openshift/release/pull/7154 installed the RT kernel...
=> Revert "Temporarily disable RT kernel"

hack/deploy.sh, hack/wait-for-mcp.sh
- Suppress some output during deployment (except during last iteration) and waiting for MCP
- Give operator less time for doimg its work, 30s should be enough
- Revert MCP wait time to old value (there always was a real issue when we run into the timeout)
=> Be less verbose, decrease wait times

functests/performance/cpu_management.go
in guaranteed mode, pod can land on any NOT reserved cpu (not just isolated one)
Signed-off-by: Yuval Kashtan <yuvalkashtan@gmail.com>
=> fix guaranteed and cpu affinity tests

.gitignore, Makefile, pkg/utils/csvtools/csvtools.go, tools/csv-generator/csv-generator.go, tools/csv-replace-imageref/csv-replace-imageref.go
This patch adds a tool to just and only update the image references
in a CSVs.
We want to use this tool to support the upgrade flows when
we will have more than one stable release.
This way, we will be able to update the older CSVs automatically
from a newer release with minimal changes.
Say, the manifest image of version N could update the bundled
manifests of version N-1 with minimal changes, thus simplifying
the upgrade graphs.
The intended overall flow is the following:
When we release version Y, we will include manifest bundles for older
versions (version Y-1 to say the least).
If a bugfix comes in stream Y-1, with this tool will have the *option*
to pull the newer version in the current Y version and release in the
manifest bundles.
Without this patch, we have only two options:
1. …
=> tools: add a simpler tool to update the image ref

functests/performance/updating_profile.go, hack/run-functests.sh
In this func test we are verifying that all profile parameters can be changed. Unfortunately, after running it - some other functional tests might be failed. 
I didn't find good solution how to postpone running this test until all other will be finished, so I would be much appreciated for any advises - what is the best way to manage it.
=> Add functional tests - updating performance profile

functests/performance/performance.go
Test runs that have a profile name combined with a prefix are not able to find the new merged tuned profile we create for performance tunings.
=> Fix performance test for merged profile

functests/test_suite_test.go, go.mod, go.sum, vendor/kubevirt.io/qe-tools/LICENSE, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go, vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go, vendor/modules.txt
This tool allows us to export results of testing to polarion.
For example, running this command will start tests and create polarion_results.xml file that can be imported to polarion:
_GOFLAGS=-mod=vendor ginkgo functests -- -ginkgo.skip "Updating parameters in performance profile" -polarion-execution=true -polarion-custom-plannedin=OCP_4_4_Code_Freeze -polarion-project-id=OSE -polarion-report-file=/tmp/polarion_results.xml --test-id-prefix=CNF_4_4_Compute_
=> Add Polarion reporter

openshift-ci/Dockerfile.registry.build
CI moved to a new cluster, and there still is no env var availabel during the image build step. So just hardcode the new URL and hope it won't change too often...
=> Fix CI registry URL

functests/performance/performance.go, functests/performance/topology_manager.go, functests/utils/nodes/nodes.go, functests/utils/pods/pods.go, hack/deploy.sh, openshift-ci/Dockerfile.registry.build
1. CI cluster was reverted to old one, so change registry URL image... again
2. OCP was rebased on k8s 1.18, which resulted in the following issues:
a) `ocp apply -f` fails to deploy ANY resource if ONE of them has an unknown kind. So apply all one by one, else our loop-until-succeed deployment doesn't work (profile can't be deployed because CRD doesn't exist in 1st iteration(s)
b) functests: `oc rsh` aka `kubectl exec` fails with `kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.`. So let's add some "--". Update: `oc rsh` still does not work, but `oc exec -i` does, so using that on everywhere.
=> Fix CI (several issues)

functests/performance/updating_profile.go, functests/utils/utils.go
For better interaction with Polarion it would be good to divide one big test on small parts
=> Divide updating profile tests for better interraction with polarion

functests/performance/updating_profile.go, functests/utils/profiles/profiles.go
The additional check in this PR ensures that non-RT kernel is
installed when realTimeKernel is set to false
=> Ensure non-RT Kernel installed when realTimeKernel is false

pkg/controller/performanceprofile/performanceprofile_controller.go, pkg/controller/performanceprofile/performanceprofile_controller_test.go, pkg/controller/performanceprofile/status.go
Add additional status fields to the Performance Profile CR that would provide additional information that would be useful for an admin to debug in case of issue:
When status of machine config pools that are attached to the performance profile are in a degraded state the performance profile status will be degraded and will contain the machine config pool failure message.
=> Add Informational status reporting on Performance Profile CR against Machine config pools

hack/wait-for-mcp.sh
We see some CI jobs failing on this without seeing an actual issue.
Signed-off-by: Marc Sluiter <msluiter@redhat.com>
=> Increase MCP update timeout

functests/performance/performance.go, functests/utils/nodes/nodes.go
borrow/import a tiny part of the k8s e2e test framework
to log messages in our tests, and use it.
We want to test failures to be as easy as possible to troubleshoot,
and for this purpose we add logging to the most critical and common
operations (more to be added in future patches)
The logs will be visible only when/if the test fail.
=> tests: better logs

functests/performance/performance.go, functests/performance/updating_profile.go
This will make it possible to filter tests when consuming as vendored dependencies.
=> Add missing performance tags.

functests/1_performance/cpu_management.go, functests/1_performance/hugepages.go, functests/1_performance/rt-kernel.go, functests/1_performance/topology_manager.go, functests/utils/images/images.go, functests/utils/pods/pods.go
Refactoring the images we use for tests, and provide a way to override the registry
they are fetched from.
The images are built from the dockerfiles being added in https://github.com/openshift-kni/cnf-features-deploy/pull/151 
They are currently being pushed to quay.io/fpaoline , a followup will mirror them on quay.io/openshift-kni
=> Add support for running tests in a disconnected environment.

functests/0_config/test_suite_performance_config_test.go, functests/1_performance/test_suite_performance_test.go, functests/2_performance_update/test_suite_performance_update_test.go, functests/utils/client/clients.go
Exiting in init() do not allow the tests to run in dryRun mode because the tests exit before constructing the gingko tree and calling it.
Here we publish the information in a variable and check it before running the suite.
=> Don't exit if the client configuration is not valid.

openshift-ci/Dockerfile.tools
- smaller base image
- run yum clean all
- install go directly instead gimme
- clean go cache, src and pkg
old image 1,3 GB (566 MB compressed on quay.io)
new: 884 MB (314 MB compressed)
NOTE: OpenshiftCI uses the build image from master, so any CI run on this PR does not prove that this change works. I tested the image on drone.io though, so I'm optimistic that it will.
=> Smaller build image

.drone.yml, Makefile, cmd/manager/main.go, hack/unittests.sh, version/version.go
Added unit test code coverage using drone.io and coveralls.io
In order to prevent that the build tool image needs to be built for every PR change, it is built on merges only.
Closes #18 
/hold
Let's see if it works...
=> Unit test code coverage

hack/csv-generate.sh, tools/csv-generator/csv-generator.go
This patch renames for consistency the `-inject-annotations-from`
option to `-annotations-from` - so all the options now look like
`-*-from`. We fix all the usages in the source tree.
Additionally, let's also use in the generator script the option
to replace the CSV description. This is opt-in as the rest of the
replacement options.
=> cleanup: streamline and use csv-generator options

.gitignore, Makefile, hack/csv-generate.sh, pkg/utils/csvtools/csvtools.go, tools/csv-generator/csv-generator.go, tools/csv-replace-imageref/csv-replace-imageref.go
In this PR we backport all the improvements made in the 4.5 branch, to make 4.4 maintenance easier and more like 4.5.
No one of these patches actually affects the operator, but rather only the release process and the metadata handling, so the risk is very low.
=> [release-4.4] align the csv processing tools with the improvements in the 4.5 branch

functests/1_performance/cpu_management.go, functests/1_performance/hugepages.go, functests/utils/images/images.go, functests/utils/pods/pods.go
We are replacing the various test images packing everything inside the cnf tests image.
This reduces the number of images we need to ship.
=> Use the cnf tests image as container image for tests pod.

functests/performance/updating_profile.go, functests/utils/utils.go
This is a cherry-pick of #158 
this block is removed since we don't have topologyManager in 4.4:
`			profile.Spec.NUMA = &performancev1alpha1.NUMA{
TopologyPolicy: &policy,
}`
/assign @gsr-shanks 
/assign @slintes
=> [release-4.4] Divide updating profile tests 

functests/1_performance/cpu_management.go, functests/1_performance/hugepages.go
We align the waiting timeout to the other pods.
=> Increase the waiting timeout for the stress pod, now using the cnf tests image

functests/utils/client/clients.go
Just always retry, it didn't catch some errors for which it should have retried (connection refused e.g.)
=> Better retry for getting resources in tests

functests/1_performance/hugepages.go
Possible the race, when we fetch free hugepages before the kernel updated it.
=> e2e: hugepages: add wait on calculation of allocated hugepages

build/assets/tuned/openshift-node-performance, functests/1_performance/performance.go, functests/2_performance_update/updating_profile.go, functests/3_performance_status/status.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go, pkg/controller/performanceprofile/performanceprofile_controller_test.go
The wrong kernel argument was set in base profile for cpu isolation (done as an equivalent for tuned realtime profile) 
changed from isolated_cpus to isolcpus
**Note**:  This fix is intended for 4.6 and above (currently fixes an u/s change made in https://github.com/openshift-kni/performance-addon-operators/pull/190)
=> Fix realtime kernel argument in base profile

functests-extended/1_performance_operator_upgrade/upgrade_operator.go, hack/run-upgrade-tests.sh
there was wrong IMAGE_TAG, so upgrade test didn't work as expected (subscription channel changed to 4.6.0, but CSV remained 4.5.0)
We didn't have CSV verification, so didn't catch this issue..
=> fix for operator upgrade test

.drone.yml, must-gather/Dockerfile, must-gather/collection-scripts/gather, must-gather/collection-scripts/namespace, must-gather/collection-scripts/version, openshift-ci/Dockerfile.must-gather
This PR adds must-gather support for performance-addon-operator.
We intentionally collect everything which concerns the PAO operativity, ignoring any overlap or duplication with other layered images.
Worth noting this is especially true for the [sriov network operator](https://github.com/openshift/sriov-network-operator/tree/master/must-gather) which is very very likely to be installed on the same cluster on which PAO runs.
=> must-gather: initial integration

Makefile, README.md, cluster-setup/upgrade-test-cluster/performance/performance_profile.yaml, functests-extended/1_performance_operator_upgrade/upgrade_operator.go, functests/utils/consts.go, hack/run-upgrade-tests.sh, hack/wait-for-mcp.sh
- it runs all other tests after upgrade
- option to run on a cluster with pre-installed profile
- option to run it on d/s
=> Improvement for operator upgrade test:

functests/1_performance/performance.go, pkg/controller/performanceprofile/performanceprofile_controller.go, pkg/controller/performanceprofile/performanceprofile_controller_test.go, pkg/controller/performanceprofile/resources.go
This PR comes to remove outdate tuned CR that do not match the expected name that is generated from their performance profile owner.
This arose from upgrade procedures where tuned generate name differs from the previous version and resulted in outdated tuned CR that were not removed from the cluster.
=> Remove outdated tuned CR owned by a performance profile

Makefile, README.md, cluster-setup/upgrade-test-cluster/performance/performance_profile.yaml, functests-extended/1_performance_operator_upgrade/upgrade_operator.go, functests/utils/consts.go, hack/run-upgrade-tests.sh, hack/wait-for-mcp.sh
This is a cherry-pick of #265
- run all tests after upgrade
- run on a cluster with pre-installed profile
- allow to run on d/s
=> [release-4.5] Improvement for operator upgrade test

functests/1_performance/performance.go, pkg/controller/performanceprofile/performanceprofile_controller.go, pkg/controller/performanceprofile/performanceprofile_controller_test.go, pkg/controller/performanceprofile/resources.go
This is a cherry-pick of #268
This PR comes to remove outdated tuned CR that do not match the expected name that is generated from their performance profile owner.
This arose from upgrade procedures where tuned generate name differs from the previous version and resulted in outdated tuned CR that were not removed from the cluster.
=> [release-4.5] Remove outdated tuned CR owned by a performance profile

must-gather/Dockerfile, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_nodes, must-gather/node-gather/daemonset.yaml, must-gather/node-gather/namespace.yaml, must-gather/node-gather/serviceaccount.yaml, openshift-ci/Dockerfile.must-gather
must-gather: collect basic HW node topology
This patch enhance must-gather to collect basic information about
the HW topology of the nodes. We use standard system utilities like
`lspci -nvv` and `lscpu -e`.
We use the same approach pioneered in cnv-must-gather to collect
data from worker nodes.
When we reach the `gather_node` stage, we create a daemonset which
will run on each worker nodes. Thanks to this daemonset, we create
hollow empty privileged pods. Privileged pods are needed to be able
to access the worker node `/proc` and `/sys` pseudofs.
Once the daemonset is ready, we iterate over all the worker nodes
and we run our collection programs (lscpu, lspci...) in the privileged
pods.
When we collected all the information we need, we clean up after
ourselves removing the daemonset with …
=> enhance must-gather to get the basic node HW topology

must-gather/collection-scripts/gather_nodes, must-gather/node-gather/daemonset.yaml
Further testing revealed we don't actually need the host mounts
in the current scenario (just run lspci and lscpu).
We already get /proc and /sys out of the box.
Also, remapping the host /proc inside the container was just wrong
and sometime lead to
```
container create failed: time="2020-06-17T09:06:26Z" level=error msg="container_linux.go:349: starting container process caused \"set process label: open /proc/self/task/1/attr/exec: no such file or directory\""
container_linux.go:349: starting container process caused "set process label: open /proc/self/task/1/attr/exec: no such file or directory"
```
It's just simpler and safer to avoid the mount until there is
a clear and obvious need for them.
=> must-gather: remove unneeded volume mount

must-gather/Dockerfile, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_nodes, must-gather/collection-scripts/namespace, must-gather/collection-scripts/version, must-gather/node-gather/daemonset.yaml, must-gather/node-gather/namespace.yaml, must-gather/node-gather/serviceaccount.yaml, openshift-ci/Dockerfile.must-gather
The performance-operator can be deployed in a namespace
different from the one we recommend, hence the `gather`
logic could be a bit smarter and try to figure out.
must-gather collects basic information about
the HW topology of the nodes. We use standard system utilities like
`lspci -nvv` and `lscpu -e`.
We use the same approach pioneered in cnv-must-gather to collect
data from worker nodes.
When we reach the `gather_node` stage, we create a daemonset which
will run on each worker nodes. Thanks to this daemonset, we create
hollow empty privileged pods. Privileged pods are needed to be able
to access the worker node `/proc` and `/sys` pseudofs.
Once the daemonset is ready, we iterate over all the worker nodes
and we run our collection programs (lscpu, lspci...) in the privileged
pods.
When …
=> [release-4.5] backport must-gather integration

must-gather/Dockerfile, must-gather/collection-scripts/gather, must-gather/collection-scripts/gather_nodes, must-gather/collection-scripts/namespace, must-gather/collection-scripts/version, must-gather/node-gather/daemonset.yaml, must-gather/node-gather/namespace.yaml, must-gather/node-gather/serviceaccount.yaml, openshift-ci/Dockerfile.must-gather
The performance-operator can be deployed in a namespace
different from the one we recommend, hence the `gather`
logic could be a bit smarter and try to figure out.
must-gather collects basic information about
the HW topology of the nodes. We use standard system utilities like
`lspci -nvv` and `lscpu -e`.
We use the same approach pioneered in cnv-must-gather to collect
data from worker nodes.
When we reach the `gather_node` stage, we create a daemonset which
will run on each worker nodes. Thanks to this daemonset, we create
hollow empty privileged pods. Privileged pods are needed to be able
to access the worker node `/proc` and `/sys` pseudofs.
Once the daemonset is ready, we iterate over all the worker nodes
and we run our collection programs (lscpu, lspci...) in the privileged
pods.
When …
=> [release-4.4] backport must-gather integration

functests/1_performance/cpu_management.go
There is a different kernel scheduler name in RT and non-RT kernels, this small fix verifies both of them.
=> fix for test 28026 (rcu_sched|rcu_preempt)

must-gather/README.md
The documentation is minimal because the content is well covered by the OCP docs.
=> must-gather: add basic doc in README

functests/utils/clean/clean.go
By adding this method, we allow external suites consuming these tests to be able to clean all the leftovers all together.
=> Add a clean.All method that can be exported and consumed externally.

functests/1_performance/performance.go
Machine-config-operator introduced a new bug, it does not preserve kernel arguments order, this bug affects only hugepages parameters(I know only these parameters hardly coupled `hugepagesz` and `hugepages`). In general, the test should not verify the order of the arguments and it should be checked under the separate test(multiple hugepages test). 
`Expect(cmdline).To(ContainSubstring(additionalArgs))` can check if
the `[]byte` contain the string, because it casts it to the string, but when it fails,
it prints the original value of `[]byte`.
=> e2e: change additional kernel arguments check

Makefile
Add targets and rules to create the must-gather image.
The end goal is to have our CI automatically create those images
nightly, not only on releases.
=> Makefile: add targets for must-gather

functests/1_performance/cpu_management.go
Commit f5667ceafe88a (fix guaranteed pod cpu test) removed
the initialization of isolatedCPU package variable, however
the tests (e.g. test_id:28026 )need it for profiles with
balanceIsolated parameter set to false.
Init the value from the profile.
=> functests/cpu_management: fix test when balanceIsolated=false

Makefile, deploy/metadata/performance-addon-operator/4.6.0/annotations.yaml, openshift-ci/Dockerfile.metadata
Not long ago the OLM gained support for the OPM tooling, which changes
the way we pack and deliver the metadata to be consumed by the OLM
itself. The new, recommended flow, makes use of the so-called "operator
bundles" and of the "index images".
See: https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md
For our intents and purposes, the main benefit here is that we don't
need to maintain anymore binary registry images, but rather only
much simpler and less challenging metadata images.
=> metadata: add metadata image, to be used with OPM

must-gather/collection-scripts/gather_nodes
Once the daemonset created, all initial values under the daemonset
status equal to 0, it can take some small amount of time until the
controller will update the status values.
Added additional check to see that the desired number of nodes does
not equal to 0.
=> must-gather: fix the ds readiness check

build/assets/tuned/openshift-node-performance, functests/1_performance/performance.go, functests/2_performance_update/updating_profile.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go, pkg/controller/performanceprofile/performanceprofile_controller_test.go
Tuned added support for the managed_irq flag of isolcpus kernel parameter.
Set the flag in order to move kernel managed IRQs out of  isolated cores in case "StaticIsolation" is enabled.
Update the tests to include the new flag.
=> add support for isolate_managed_irq

functests/1_performance/cpu_management.go, functests/1_performance/hugepages.go, functests/1_performance/performance.go, functests/1_performance/topology_manager.go, functests/2_performance_update/updating_profile.go, functests/3_performance_status/status.go, functests/utils/consts.go, functests/utils/nodes/nodes.go
Currently the nodes for e2e tests are selected by a 'role' label.
Sometimes the granularity is not enough and there is a need to filter
the 'role' nodes using a standard label.
Allow the filtering based on a "NODES_SELECTOR" environment variable.
=> functest/nodes: allow nodes matching by an optional selector

functests/0_config/config.go, functests/1_performance/cpu_management.go, functests/1_performance/hugepages.go, functests/1_performance/performance.go, functests/1_performance/rt-kernel.go, functests/1_performance/topology_manager.go, functests/2_performance_update/updating_profile.go, functests/3_performance_status/status.go, functests/utils/consts.go, functests/utils/discovery/discovery.go, functests/utils/mcps/mcps.go, functests/utils/nodes/nodes.go, functests/utils/profiles/profiles.go
The performance tests should be able to work in "discovery mode", meaning that they rely on the feature they want to test to be configured on the cluster use use the default test profile the performance tests create. 
Discovery mode is be enabled the environment parameter DISCOVERY_MODE=1/ t / T / TRUE / true /True
=> Make the performance tests work in discovery mode

functests/1_performance/performance.go
Injection test that was added never passed upgrade tests due to : https://bugzilla.redhat.com/show_bug.cgi?id=1858347 
Temporarily skipping this test until the BZ is either resolved and/or needs test amendments to release the rest of the upgrade test flow.
=> Temporarily skip initramfs injection test due to BZ#1858347

hack/generate-manifests-index.sh
add missing flag to make the script work nicely with selinux.
Previously, without this flag, the script used to fail with
panic: unable to open database file
selinux log revealed the culprit:
avc:  denied  { write } for  pid=35664 comm="initializer" name="database" dev="dm-4" ino=393268 scontext=system_u:system_r:container_t:s0:c809,c992 tcontext=unconfined_u:object_r:user_tmp_t:s0 tclass=dir permissive=0
=> generate-manifests-index.sh: fix volume mount

build/assets/configs/99-runtimes.conf, deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml, deploy/role.yaml, functests/1_performance/cpu_management.go, functests/utils/pods/pods.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/controller/performanceprofile/components/runtimeclass/runtimeclass.go, pkg/controller/performanceprofile/performanceprofile_controller.go, pkg/controller/performanceprofile/performanceprofile_controller_test.go, pkg/controller/performanceprofile/resources.go
Functionality to disable/enable the CPU load balancing will be implemented on the CRI-O level, the code under the CRI-O will disable/enable CPU load balancing only when:
- the pod uses `performance-<profile_name>` runtime class
- the pod has `cpu-load-balancing.crio.io: true` annotation
The performance-addon-operator will be responsible for the creation of the high-performance runtime handler config snippet, it will have the same content as default runtime handler, under relevant nodes, and for creation of the high-performance runtime class under the cluster.
A user will be responsible for specifying the relevant runtime class and annotation under the pod.
=> Deploy the custom runtime via the operator

openshift-ci/Dockerfile.bundle.ci, openshift-ci/Dockerfile.bundle.upstream.dev
We don't really need the "FULL_OPERATOR_IMAGE" in the bundle
Dockerfiles: it is only needed in the build step, when we update the
manifests. IOW, when we build the containers, the replacement must have
been done already.
Clean up for clarity; the variable was left over because of a copypaste
artifact.
=> Dockerfiles: remove useless argument

deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml, docs/performance_profile.md, pkg/apis/performance/v1/performanceprofile_types.go, pkg/apis/performance/v1alpha1/performanceprofile_types.go
Add notice regarding using isolated CPUs as complementary to reserved CPUs.
=> Update the description of the isolated CPUs field

functests/0_config/config.go, functests/1_performance/hugepages.go, pkg/controller/performanceprofile/components/profile/profile.go, pkg/controller/performanceprofile/components/profile/profile_test.go
Multiple hugepages sizes support feature was promoted to beta under
the Kubernetes 1.19, it gives us possibility to support multiple
hugepages sizes under the PAO, without need to enable additional
feature gate.
=> Remove hugepages multiple sizes validation

hack/clean-deploy.sh
this is a fix for nodeSelector parser that gets incorrect data:
```
$ oc get performanceprofile.performance.openshift.io/manual -o=jsonpath='{.spec.nodeSelector}' | awk -F'[/:]' '{print $2}'
worker-cnf"
```
as result node label and mcp were not removed.
=> fix for PAO cleaning script

hack/generate-manifests-index.sh
It seems that at least from version "18.02.0-ce"
the `initializer` found in the
`quay.io/operator-framework/upstream-registry-builder` image requires a
more precise path specification to read the manifests.
We fix our scripts to comply.
This issue was not triggered earlier on CI because we don't build *index*
images in CI, in turn caused by current CI limitations; we only build
bundle images in CI.
=> index: fix building of the index images

openshift-ci/Dockerfile.registry.build
The CI job was moved to the different cluster, so we should to
adpat the registry URL.
=> Change the CI registry URL

Makefile, README.md, functests/4_latency/Dockerfile, functests/4_latency/latency.go, functests/4_latency/run-tests.sh, functests/4_latency/test_suite_latency_test.go, hack/build-test-bin.sh, hack/run-functests.sh
As first step we should only to test that the oslat image
works correctly, the next step will be to define uppper and
lower bounds and to verify that the latency has value between
bounds.
The latency-test container image gives possibilty to run the latency
tests without need to install go, ginkgo or other go related modules.
To run the latency test inside of container:
```
docker run --rm -v /home/alukiano/Downloads/cluster/auth/kubeconfig:/kubeconfig -e KUBECONFIG=/kubeconfig -e LATENCY_TEST_RUN=true -e LATENCY_TEST_RUNTIME=60 -e OSLAT_MAXIMUM_LATENCY=700 alukiano/latency-test:4.6-snapshot /usr/bin/run-tests.sh
```
You can run the container with different ENV variable, but the bare minimum is to pass
`KUBECONFIG` mount and ENV variable, to give to the test access to the cluster and …
=> Provide the latency e2e test and container image

pkg/controller/performanceprofile/components/consts.go, pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go
Some architectures such as arm, powerpc, and sparc set up hstates for all supported sizes.
Other architectures such as riscv, s390, and x86 only set up hstates for those requested on the command line with hugepagesz=.
Depending on config options, x86 and riscv may or may not set up PUD_SIZE hstates.
So once you specify the `default_hugepagesz` equal to 1G,
the kernel will remove all 2M huge pages related files and directories from the filesystem.
You can find more details under the kernel email thread - https://lkml.org/lkml/2020/3/5/1113.
And it will prevent to allocate 2M huge pages on the specific NUMA node because the expected file does not exist.
To W/A the problem, once a user will request 2M huge pages allocation on the
specific NUMA node and the `default_hugepagesz` equal to 1G, …
=> Add dummy 2M huge pages kernel arguments

openshift-ci/Dockerfile.registry.build
Looks like CI was moved to another cluster again, let's switch it and check if tests passed
=> Revert the CI registry URL back to registry.svc.ci.openshift.org

docs/configuration_hotfixes.md
Update the API references to v1.
Leave the README's reference to the way the operator
was created to v1alpha1.
=> docs: Update the docs to reflect the API is now v1

functests/1_performance/cpu_management.go, functests/1_performance/hugepages.go, functests/1_performance/performance.go, functests/1_performance/rt-kernel.go, functests/1_performance/topology_manager.go, functests/2_performance_update/updating_profile.go, functests/3_performance_status/status.go, functests/4_latency/latency.go, functests/utils/consts.go, functests/utils/discovery/discovery.go
If discovery mode is enabled but no profile is installed the tests currently panic.
Here, we are forcing all the tests to skip if that happens, providing the reason.
=> Bug 1872417: E2e tests - do not panic in discovery mode with no profile installed.

functests/1_performance/cpu_management.go
Test fixed to check a cpuset of isolated cpus :  if the amount of isolated cups is 1 or 0 then tests in discovery mode will be skipped with : "Skipping tests since there are insufficient isolated cores to create a stress pod"
=> Fix CPU managment test to check for right numbers of isolated CPUs

deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml, hack/csv-generate.sh, hack/generate-manifests-index.sh, hack/generate-manifests-tree.sh
1. csv-generate: pass `--from-version` parameter to prevent errors
from the `operator-sdk generate csv` and create the separate ENV
variable for the CSV channel. Also, copy CRD and package yamls to the
repository directory after the generation to have updated files.
2. generate-manifest-index: remove the database folder before generating
the new bundle database.
3. generate-manifests-tree: fix the path for generated files.
=> Fix generate scripts to support generation of z-stream manifests

functests/utils/nodes/nodes.go
Flags for the RT kernel configuration are different under
`rhel-rt-8.2` and `rhel-rt-8.3`, `CONFIG_PREEMPT_RT_FULL` vs
`CONFIG_PREEMPT_RT`. To avoid need to change the flag check
we have better check if the RT kernel is enabled via
`/sys/kernel/realtime` file.
=> e2e tests: fix the RT kernel check

build/assets/tuned/openshift-node-performance, functests/1_performance/performance.go
Enable by default the stall daemon in the base profile.
Stall daemon is supported by NTO : https://github.com/openshift/cluster-node-tuning-operator/pull/152  
and tuned service plugin: https://github.com/redhat-performance/tuned/pull/293
=> Enable support for stall daemon in base profile

functests/1_performance/cpu_management.go
Cpu affinity test may fail in scenario when we have some CPUs that not a part
of Reserved or Isolated groups. After changes in this PR we will be verifying
that rcu processes are not running on isolated cores.
=> Fix for CPU Affinity mask test

pkg/controller/performanceprofile/components/tuned/tuned.go
Set Tuned CR to a higher priority (20) in order to avoid collisions with NTO profiles with the same priority (with emphasis on deploying profiles on mater nodes )
=> Set Tuned created CR to higher priority

must-gather/collection-scripts/gather_nodes, must-gather/collection-scripts/namespace
`oc` moved gather containers under `containers` in
https://github.com/openshift/oc/commit/dc196cab08e71be45fb81a04f202525a6cb69689
We need to align with this change.
=> must-gather: fix container image lookup

hack/run-functests.sh
Under our CI very high percentage of failures happens
under the 2_performance_update test suit because of the bug
https://bugzilla.redhat.com/show_bug.cgi?id=1865839.
Disable temporary the 2_performance_update test suit until
the bug will be fixed.
=> Do not run 2_performance_update test suit

deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml, deploy/operator.yaml, functests/0_config/config.go, functests/1_performance/performance.go, functests/utils/consts.go, functests/utils/pods/pods.go
Followup of https://github.com/openshift-kni/performance-addon-operators/pull/351 with the functest moved out from the `0_config` suite.
=> Pao run master nodes

functests/1_performance/cpu_management.go, functests/1_performance/performance.go, functests/4_latency/latency.go, functests/utils/clean/clean.go, functests/utils/profiles/profiles.go
In our test suite we must ensure deleted objects are really gone.
Add WaitForDeletion helper for profiles, and use it in the test which previously just used other means to check a profile was gone.
Make sure we consistently wait for pod deletion once we delete a pod.
=> functests: ensure deleted objects are really gone

cluster-setup/mcp-only-cluster/performance/kustomization.yaml, cluster-setup/mcp-only-cluster/performance/machine_config_pool.yaml, deploy/metadata/performance-addon-operator/4.5.1/annotations.yaml, deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.5.1/performance.openshift.io_performanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml, openshift-ci/Dockerfile.bundle-4.5.ci
- add 4.5.1 CSV
- add 4.5 bundle docker image to test possibility to build
index image that will include multiple versions
- add mcp-only-cluster setup manifests because all other
components deployed by the OpenShift CI
=> Adaptation to build operators under the OpenShift CI

build/assets/scripts/hugepages-allocation.sh
The allocation of hugepages dynamically via the allocation
the script sometimes failed(the reason still under the investigation)
and does not allocate the specified number of hugepages.
And on the second try, the allocation succeeds. To try allocation
again we added the while loop that will try to allocate again for
the whole minute with the frequency one sample per second.
Fixes #279 
=> Add a loop to the hugepages allocation script

functests/performance/cpu_management.go, openshift-ci/Dockerfile.registry.build
Changed the pid that verifies cpu affinity mask (now using pid 1) for having more generic approach
Removed colon for reservedCPUSet variable in BeforeEach() (otherwise this variable is Null in tests)
(technically, same changes as we had in commit: https://github.com/openshift-kni/performance-addon-operators/pull/331/commits/5f545eb31f1e18c5163851c0211b455d44ea3d1d, can't do cherry pick because of different functest folder structure)
=> [release-4.4] Fix for cpu affinity test

Makefile, cluster-setup/ci-upgrade-test-cluster/performance/kustomization.yaml, cluster-setup/ci-upgrade-test-cluster/performance/performance_profile.yaml, hack/ci-run-upgrade-test.sh
Now that the CI install for use the operator, we should only:
- deploy MCP
- label the worker with the worker-cnf label
- deploy the performance profile
=> Provide manifests and script to run upgrade test under the CI

functests/1_performance/cpu_management.go, openshift-ci/Dockerfile.registry.build
Under our CI it happens pretty often that the test
does not get the path to the container cpuset cgroup,
probably it takes some time to sync cgroup changes between host
and machine-config-daemon container.
To see if it indeed the case I will add `Eventually` that will try
to fetch container cpuset cgroup for two minutes with 30 seconds samples.
=> e2e: fix the runtime class test

cluster-setup/ci-upgrade-test-cluster/performance/kustomization.yaml, cluster-setup/ci-upgrade-test-cluster/performance/performance_profile.yaml, cluster-setup/mcp-only-cluster/performance/kustomization.yaml, cluster-setup/mcp-only-cluster/performance/machine_config_pool.yaml, deploy/metadata/performance-addon-operator/4.5.1/annotations.yaml, deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.5.1/performance.openshift.io_performanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml, hack/run-upgrade-tests.sh, openshift-ci/Dockerfile.bundle-4.5.ci
Now that the OpenShift CI creates for us index image and deploy
the operator via OLM, we do not need to deploy these pieces by ourselves.
- provide mcp-only cluster to deploy only the MCP
- provide 4.5.1 CSV and bundle docker file for the upgrade test
- make possible to specify the cluster type for the upgrade test script
=> [release-4.6] ci: adaptations to operator pipeline

hack/run-upgrade-tests.sh
Deploying PAO should be optional for running upgrade tests in d/s environment (since we already have it deployed thru d/s stuff)
=> Fix for upgrade script: make deploying PAO optional

functests/utils/profiles/profiles.go
When the range used under the `for` loop it will create a new
scoped variable, that will have a different value for each loop cycle.
Once you will get the pointer on this variable it will point to the latest
element that the `for` loop will pass.
=> e2e: fix getting a profile by the node selector

functests/utils/utils.go
We expect nothing useful from stderr, so let's not even read it
Capturing stderr is useful to troubleshoot failures, but it should not mixed with stdout and should be captured and kept separate.
=> functests: don't read stderr when getting logs

README.md, functests/4_latency/latency.go
We add an optional delay before to actually run the latency test
to give more room to the kubelet reconcile loop to kick in and make
sure all the pods are running in the proper cpusets.
Without this delay is harder to guarantee that other pods do not
run on exclusively allocated cpus.
Please note that using a delay is a mitigation of the inherent (lack of)
synchronization between the test and the kubelet cpumanager reconcile
loop. It is very possible that the reconciliation happens fast enough
even with initial zero delay, so this change add a test/troubleshooting
knob rather than fixing a misbehaviour.
=> latency-test: add and pass initial delay

functests/3_performance_status/status.go, functests/utils/profiles/profiles.go, pkg/controller/performanceprofile/components/profile/profile.go, pkg/controller/performanceprofile/components/profile/profile_test.go, pkg/controller/performanceprofile/components/utils.go, pkg/controller/performanceprofile/components/utils_test.go
We always assume, and document, that the reserved and
isolated cpus set must not overlap.
Add some validation code to enforce this constraint.
=> controller: validation: check for cpu cores split

functests/1_performance/cpu_management.go
Fix runtime class test failures when it runs on the environment with more than one worker-cnf node.
- add proper node selector to the pod
- revert `Eventually` that I added before because thought it was some race
the condition between the start of the container and the update of the cgroup
=> e2e: fix runtime class test failures

functests/2_performance_update/updating_profile.go
test_id:28025 Test failed on the node with more than 4 CPUs. Switching
verification to regexp should make it more flexible.
Note: currently updating tests are disabled on CI because of bug so the fix will not be checked. I verified in manually on my local cluster.
=> Fix for update test - make verification of cpu affinity mask flexible

functests/3_performance_status/status.go
For some reason old approach with changing currentConfig does not work -
sometimes it takes more than 30 minuted for MCP to update the status to
"Degraded"
MCO team adviced to rewrite the test - put the node/mcp to degraded state
by creating bad machineConfig.
=> [release-4.6] Fix for test - MCP status in performance profile

functests/1_performance/cpu_management.go
It will prevent panics under our CPU tests:
```
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:199
Full Stack Trace
github.com/openshift-kni/performance-addon-operators/functests/1_performance.glob..func1.1()
/go/src/github.com/openshift-kni/performance-addon-operators/functests/1_performance/cpu_management.go:54 +0x506
github.com/openshift-kni/performance-addon-operators/functests/1_performance_test.TestPerformance(0xc0002a9a00)
/go/src/github.com/openshift-kni/performance-addon-operators/functests/1_performance/test_suite_performance_test.go:49 +0x239
testing.tRunner(0xc0002a9a00, 0x1831a28)
/usr/local/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
/usr/local/go/src/testing/testing.go:960 +0x350
```
Signed-off-by: …
=> e2e: check that it no error before accessing the profile fields

deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml
Replace only the REPLACE_IMAGE place holder, other than that
all the files are exactly as in release-4.6 branch.
=> deploy: Rollback the 4.6 CSV and CRD to before the webhook conversion

hack/run-functests.sh
- replace `keepGoing` flag by `failFast`, our CI requires that all tests should pass,
it no taste to wait until all tests will finish to run if one of them failed
- to avoid flakiness, add `flakeAttempts=2`, so once test fail the ginkgo will re-run it once
=> Change functest run parameters

README.md, hack/generate-index-database.sh
- output the log from the opm container
- wait for opm container to stop before copy the generated files
=> Small improvements to the generate-index-database script

api/v2/performanceprofile_types.go, config/crd/bases/performance.openshift.io_performanceprofiles.yaml, deploy/olm-catalog/performance-addon-operator/4.7.0/performance.openshift.io_performanceprofiles_crd.yaml, docs/performance_profile.md
Our doc generator set all fields with `omitempty` directive as not
required one. So part of mandatory fields appear as not required under the documentation.
Fixes #426 
=> Remove omitempty from mandatory fields

must-gather/collection-scripts/namespace
Per https://docs.openshift.com/container-platform/4.6/scalability_and_performance/cnf-performance-addon-operator-for-low-latency-nodes.html#install-operator-cli_cnf-master
the suggested namespace is `openshift-performance-addon-operator`, so
we use it as fallback for consistency.
=> must-gather: fix fall-back namespace

functests/3_performance_status/status.go, pkg/controller/performanceprofile/components/profile/profile.go, pkg/controller/performanceprofile/components/profile/profile_test.go, pkg/controller/performanceprofile/components/utils.go, pkg/controller/performanceprofile/components/utils_test.go
It's legal, albeit probably not what users want, to
have empty sets for either reserved and isolated CPUs.
Hence make sure tests cover this case.
=> validate: check for no isolated/reserved cpus

cluster-setup/base/performance/operator_namespace.yaml, cluster-setup/base/performance/operator_operatorgroup.yaml, cluster-setup/base/performance/operator_subscription.yaml, cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml, config/rbac/role.yaml, controllers/performanceprofile_controller.go, functests-extended/1_performance_operator_upgrade/upgrade_operator.go, functests/utils/consts.go, functests/utils/namespaces/namespaces.go, functests/utils/pods/pods.go, hack/clean-deploy.sh, hack/run-upgrade-tests.sh
Allow to override the namespace name the tests wants to consume;
this is needed because when doing validation, we need to make sure to
check what was actually installed in the cluster, and there is no hard
requirement on the namespace name - only suggestions.
Additionally, change the fallback name to the one suggested in the last
docs.
=> Bug 1894861: tests: allow override operator namespace

hack/run-functests.sh
- replace `keepGoing` flag by `failFast`, our CI requires that all tests should pass,
it no taste to wait until all tests will finish to run if one of them failed
- to avoid flakiness, add `flakeAttempts=1`, so once test fail the ginkgo will re-run it once
=> [release-4.6] Change functest run parameters

hack/run-functests.sh
- replace `keepGoing` flag by `failFast`, our CI requires that all tests should pass,
it no taste to wait until all tests will finish to run if one of them failed
- to avoid flakiness, add `flakeAttempts=1`, so once test fail the ginkgo will re-run it once
=> [release-4.5] Change functest run parameters

openshift-ci/Dockerfile.registry.build
The registry image started to use the custom user, because durring the build process
it can not run the sed command under the registry folder.
```
STEP 6: RUN find /registry/performance-addon-operator-catalog/ -type f -exec sed -i "s|REPLACE_IMAGE|${REG_URL}/${OPENSHIFT_BUILD_NAMESPACE}/stable:performance-addon-operator|g" {} \; || :
sed: couldn't open temporary file /registry/performance-addon-operator-catalog/performance-addon-operator/4.4.0/sedRpZqNd: Permission denied
sed: couldn't open temporary file /registry/performance-addon-operator-catalog/performance-addon-operator/4.4.0/sediiWctc: Permission denied
sed: couldn't open temporary file /registry/performance-addon-operator-catalog/performance-addon-operator/4.4.1/sedWUwric: Permission denied
sed: couldn't open temporary file …
```
=> Change the user during the registry build

hack/run-functests.sh
- replace `keepGoing` flag by `failFast`, our CI requires that all tests should pass,
it no taste to wait until all tests will finish to run if one of them failed
- to avoid flakiness, add `flakeAttempts=1`, so once test fail the ginkgo will re-run it once
=> [release-4.4] Change functest run parameters

cluster-setup/base/performance/operator_namespace.yaml, cluster-setup/base/performance/operator_operatorgroup.yaml, cluster-setup/base/performance/operator_subscription.yaml, cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml, functests-extended/1_performance_operator_upgrade/upgrade_operator.go, functests/utils/consts.go, functests/utils/namespaces/namespaces.go, functests/utils/pods/pods.go, hack/clean-deploy.sh, hack/run-upgrade-tests.sh
Manual cherry pick of https://github.com/openshift-kni/performance-addon-operators/pull/437
Always use the namespaces suggested in the official documentation.
Allow to override the namespace name the tests wants to consume;
this is needed because when doing validation, we need to make sure to
check what was actually installed in the cluster, and there is no hard
requirement on the namespace name - only suggestions.
=> Tests: fix default namespace, and allow override

build/assets/tuned/openshift-node-performance, functests/2_performance_update/updating_profile.go
By default tuned sets the default IRQ SMP affinity to the non isolated
CPUs set.
However, when the IRQ load balancing is set dynamically depending on pod
annotations, the default IRQ SMP affinity should remain all machine
CPUs.
Fix the behavior by setting the new tuned option:
"default_irq_smp_affinity" to "ignore."
=> Fix the tuned profile when IRQ load balancing is not disabled globally

openshift-ci/Dockerfile.tools
Docker hub added rate limit that prevents from us to build
the tools image. To avoid the problem we will use the
ubi image from the redhat registry.
=> Replace tools base image from centos to ubi

build/assets/configs/99-low-latency-hooks.json, build/assets/configs/99-netdev-rps.rules, build/assets/scripts/low-latency-hooks.sh, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Add a pre-start OCI hook setting the CPUs RPS mask to the performance profile's reserved CPUs.
To-do:
- Some tests
=> machineconfig: Set RPS mask for both containers and host

build/assets/configs/99-runtimes.conf, controllers/performanceprofile_controller.go, controllers/performanceprofile_controller_test.go, docs/cpu-load-balancing.md, functests/1_performance/cpu_management.go, functests/1_performance/performance.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
- add allowed_annotations under the runtime handler configuration
- change the runtime handler name to the low-latency
- use disable value for the CPU load balancing annotation
- update the documentation
=> Align CPU load balancing functionality with the latest CRI-O changes

docs/api-versions.md, docs/irq-load-balancing.md
Document both the GloballyDisableIrqLoadBalancing field and the
annotations used to disable IRQs only for the pod CPUs.
=> docs: Add irq-load-balancing documentation

build/assets/scripts/set-rps-mask.sh, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
It turns out the veth devices are renamed as soon as they are created,
resulting in a race between that time and the time the update-rps
service handles the interface.
If the net device directory does not exist assume the net device
has already been renamed and trace it using the systemd device
dependencies.
=> machineconfig: fix the RPS boot failures

cluster-setup/ci-upgrade-test-cluster/performance/performance_profile.yaml
The wait-for-mcp script expects that the MCP will consume the
MC with the name `performance-${CLUSTER}`, but the MC name generated
by the pattern `performance-<performance-profile-name>`.
=> Fix CI upgrade test

build/assets/configs/99-runtimes.conf, controllers/performanceprofile_controller.go, controllers/performanceprofile_controller_test.go, functests/1_performance/performance.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
It was not a good idea to change the name of the generate runtime class
because the name is immutable field and during the upgrade you will have
failure:
```
2020-12-17T07:07:31.743Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "performance.openshift.io", "reconcilerKind": "PerformanceProfile", "controller": "performanceprofile", "name": "ci-upgrade-test", "namespace": "", "error": "RuntimeClass.node.k8s.io \"performance-ci-upgrade-test\" is invalid: handler: Invalid value: \"low-latency\": field is immutable"}
```
To make it possible to change the name, we should first delete the runtime class and after the
performance-addon-operator will re-create it with the updated name.
I will check under a separate PR if it is possible, but to fix the upgrade-test I will revert the …
=> Revert the change of the generated runtime class name

build/assets/tuned/openshift-node-performance
The stalld service has higher priority than `ksoftirqd`, `rcub` and `rcuc` that
can lead to the system freeze under the load pressure. To avoid it we should
raise the scheduler priority of these threads to be higher than the stalld service.
=> Bug 1905492: Update the tuned profile to set higher scheduler priority

build/assets/scripts/set-rps-mask.sh
A few service failures were spotted in a long running BM node.
It seems there may still be a race between the interface renaming
and the systemd service running the script.
Improve it by re-trying to find the renamed network device
after a few seconds.
While at it:
- do not consider not finding the device a service error, sometimes
the interfaces vanish fast.
- consider the improbable case when going over the systemd services
we find first the original device and not the new one.
=> scripts: Yet another improvement to the set-rps-mask.sh script

functests/1_performance/cpu_management.go, functests/1_performance/hugepages.go, functests/4_latency/latency.go, functests/utils/pods/pods.go
Sometimes the pod deletion fails because of the timeout, the patch
increases the timeout for pod deletion to two minutes.
=> e2e: increase the pod deletion timeout

functests/1_performance/cpu_management.go
The CPU load balancing test can fail on the environment with some additional configuration because of my assumptions that sched_domain flags for all CPUs will be the same. Now the test will fetch sched_domains for all CPUs and validate the disabling of the pod CPU versus the relevant CPU.
=> e2e: fetch sched_domains for all CPUs to validate CPU load balance disabling

build/assets/tuned/openshift-node-performance, pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go
Avoid setting real-time related parameters for the non-RT kernel.
Setting these parameters can hang the system.
- the most problematic parameter is `sched_rt_runtime_us` that can prevent to get the CPU time for some tasks with a small priority.
- the stalld service does not start without `sched_rt_runtime_us=-1`
=> Bug 1912118: does not set RT parameters for non-RT kernel

openshift-ci/Dockerfile.must-gather
it seems we forgot to update to 4.7.0 some time ago.
=> must-gather: dockerfile: rebase on 4.7.0

must-gather/collection-scripts/gather_nodes
In must-gather, we use a shell for loop to gather
the node logs for all the relevant units.
We run each gather process in background, which is a good
thing to speed up the task.
However, we need to wait for these processes to complete
before we move forward, otherwise we will terminate discarding
the background process data.
=> bug 1906355 must-gather: wait when gathering node logs

functests/0_config/config.go, functests/utils/clean/clean.go, functests/utils/mcps/mcps.go, go.mod, pkg/controller/performanceprofile/components/consts.go
In order to make the tests work with a single node cluster, every time there is a chance the node is rebooted (after applying / deleting a profile), we just need to wait for conditions without checking the errors. This is because if polling happens when the cluster is down, the api calls will fail.
=> Don't check for errors while waiting for profile to be applied.

must-gather/collection-scripts/gather_nodes
must-gather want to collect kubelet logs. Problem is: these logs can get quite big (>= 1 G each) quite fast. To save bandwidth, we compress them, saving roughly 90% of the space (e.g. from ~1G to ~100M). Using gzip inside must-gather is not unheard of, at least audit logs and network logs gatherer already do it.
To save more bandwidth:
- we restrain ourself to collect the last 8 hours of kubelet logs
- we collect kubelet logs from worker nodes only
=> must-gather: compress kubelet logs

functests-extended/1_performance_operator_upgrade/upgrade_operator.go, functests/0_config/config.go, functests/2_performance_update/updating_profile.go, functests/utils/mcps/mcps.go, functests/utils/profiles/profiles.go, hack/run-functests.sh
The bug with the rpm-ostree should be solved under the latest
4.7 RHCoS.
=> e2e: enable back update tests

build/assets/configs/99-runtimes.conf, functests/1_performance/cpu_management.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
The PAO will update the CRI-O configuration and will set infra containers
CPUs to one that specified under the performance profile.
=> Configure CRI-O infra containers CPUs

must-gather/README.md
our CI doesn't autogenerate the `latest` tag, so let's not mention it.
=> must-gather: doc: fix README

must-gather/node-gather/daemonset.yaml
reduce must-gather daemonset permissions.
No intended changes in behaviour.
=> must-gather: narrow down permissions

Makefile
We want it enabled by default.
=> Makefile: build the profile helper by default

openshift-ci/Dockerfile.bundle.ci, openshift-ci/Dockerfile.bundle.upstream.dev
let's avoid the same error we made in 4.6: elide Z version from channel
name, use only "$MAJOR.$MINOR' version.
=> bundle: make annotations consistent

build/assets/tuned/openshift-node-performance, functests/1_performance/performance.go
Service stalld is enabling high resolution timer that currently has a bug.
To avoid system hangs the PAO will not install and enable stalld by default
until bugs https://bugzilla.redhat.com/show_bug.cgi?id=1903302 and
https://bugzilla.redhat.com/show_bug.cgi?id=1912118 fixed.
=> Bug 1923220: Do not install and enable stalld service

api/v1alpha1/performanceprofile_conversion.go, api/v2/performanceprofile_conversion.go, functests/1_performance/performance.go
It possible the situation when the source conversion object has nil for
some field, but we initialize this field under the destination object.
=> Bug 1918788: Avoid unneeded object initialization during profile conversion 

openshift-ci/Dockerfile.tools
We have troubles with glibc library under the ubi8, so it can be a good reason to advance
tools image version to ubi8.
ubi8 does not have skopeo package, I can not find a single place where it should be used.
=> Update tools image to use ubi8

controllers/status.go
Remove the kubeletconfig condition status check because
kubeletconfig failure condition has the False status instead of True and I do
not really know if it some use cases when it can be True.
```
Status:
Conditions:
Last Transition Time:  2020-12-03T13:37:06Z
Message:               Error: could not find any MachineConfigPool set for KubeletConfig
Status:                False
Type:                  Failure
```
=> Fix the expected kubeletconfig failure condition status

cmd/performance-profile-creator/README.md, hack/run-perf-profile-creator.sh
It is a convenience only script that automates PAO/must-gather
images retrieval and runs the Performance Creator Tool.
Expect a must-gather tarball or run must-gather to get the data.
Mount the data directory into the container and point
the Performance Creator Tool to it.
=> hack: Add run-perf-profile-creator wrapper

must-gather/node-gather/daemonset.yaml
Using the 'Always' pull policy improves the security of this flow
and cost nothing in the common path, on which must-gather is run
rarely if ever - so the first pull need to happen anyway.
=> must-gather: use 'Always' pull policy

functests/1_performance/cpu_management.go
The default SMP affinity containers the mask for all CPUs not only
for online ones, so the test fails to verify that all online CPUs
under the default SMP affinity on the system configured with nosmt
kernel argument.
=> e2e: fix the IRQ load balancing test to work properly with nosmt

build/assets/tuned/openshift-node-performance
Under 4.6 stalld installed without systemd overlay file, so it can not be disabled via
service plugin. Remove the service section to make sure that stalld does not run under
the system.
Related to https://github.com/openshift-kni/performance-addon-operators/pull/524
=> [release-4.6] comment the stalld section

cmd/performance-profile-creator/cmd/root.go
- This patch marks reserved-cpu-count, mcp-name and rt-kernel
as required fields and are expected to be specified. In case
the user does not specify them, PPC returns an error
=> Add MCP as an argument and mark certain flags as required

cmd/performance-profile-creator/cmd/root.go
This patch ensures that the performance profile is not sent
to STDOUT in case the user specifies --help or -h flag.
Previously, the createProfile function was called from
init function resulting in creation of profile even
when the user wants to see the PPC usage using -h/--help.
=> No profile creation in case PPC is run with --help/-h

functests/utils/consts.go, functests/utils/discovery/discovery.go
Currently when running cnf-tests in discovery mode the performance
profile selector is choosing the profile in the cluster with the
most nodes using it.
When running in a cluster with more than one performance profile,
the profile selector should choose the performance profile by
NODES_SELECTOR env var if it is set.
=> Update discovery mode performance profile selector to choose by NODE_SELECTOR environment variable

must-gather/collection-scripts/gather_nodes, must-gather/node-gather/daemonset.yaml, tools/gather-sysinfo/gather-sysinfo.go
With this PR we explicitely mount host /sys and /proc inside the container, because what we care about is host content, not container content. Even if likely, we don't have record of guarantee that the container view matches the host view. Now the intent is explicit. This also allows us to narrow down further the container privileges.
=> must-gather: gather sysinfo from host data

must-gather/collection-scripts/gather_nodes, tools/gather-sysinfo/gather-sysinfo.go
`gather-sysinfo` can emit the tar file directly to stdout.
Avoiding the local file, we can simplify our gathering script and
make the process a bit faster.
=> must-gather: sysinfo: direct copy using stdout

Makefile
Let's smoothen some rough corners
- make sure `must-gather-container` trigger binary build if needed
- add `clean` shortcut
Both of the above aren't strictly needed but improve a bit the dev
experience.
=> Makefile: smoothen targets

must-gather/node-gather/daemonset.yaml
Up until now, the per-node daemonset pods had a memory limit of 50 megs.
This was pretty much a "low enough" guesstimate we did back in time as
initial assessment and we stuck to it.
Now we have `gather_sysinfo`, which needs to access quite a lot small
files, and on mid-sized multi-numa boxes (feb 2021) can easily eat 60
megs alone. Hence, we get the container OOM killed, like:
```bash
[3539462.598151] [ pid ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[3539462.607760] [3852242]     0 3852242    35869      679   172032        0         -1000 conmon
[3539462.617012] [3852256]     0 3852256   175834     1086    81920        0          -998 pod
[3539462.625977] [3852769]     0 3852769    35869      679   172032        0         -1000 conmon
[3539462.635178] …
```
=> must-gather: bump up gather pod memory limit

Makefile, hack/verify-tools.sh
This update intended to explicitely test our internal tools, which don't have explicit test coverage atm.
The update composed of two part:
1. Makefile's target (this PR)
2. Create a CI lane for the OpenShift CI (another PR will be issue soon)
=> Create CI lane to validate u/s targets and tooling

functests/1_performance/cpu_management.go
The test constantly fails under d/s CI, the reason that some of the interrupts can not be moved.
It no easy way to fix it, and until we will have some solution we need to skip the test.
=> e2e: skip the IRQ load balancing test

functests/0_config/config.go, functests/1_performance/cpu_management.go, functests/1_performance/performance.go, functests/1_performance/test_suite_performance_test.go, functests/2_performance_update/test_suite_performance_update_test.go, functests/3_performance_status/test_suite_performance_status_test.go, functests/4_latency/latency.go, functests/4_latency/test_suite_latency_test.go, functests/utils/clean/clean.go, functests/utils/client/clients.go, functests/utils/discovery/discovery.go, functests/utils/log/log.go, functests/utils/mcps/mcps.go, functests/utils/nodes/nodes.go, functests/utils/profiles/profiles.go, functests/utils/utils.go
We want to reduce the verbosity of logs output in the case when the test succeeded and provide more information only in case when the test failed.
```
Ginkgo provides a globally available io.Writer called GinkgoWriter that you can write to. GinkgoWriter aggregates input while a test is running and only dumps it to stdout if the test fails.
```
=> Bug 1885317: Provide a log package that will write to GinkgoWriter

functests/0_config/config.go, functests/1_performance/cpu_management.go, functests/1_performance/hugepages.go, functests/1_performance/performance.go, functests/1_performance/rt-kernel.go, functests/1_performance/test_suite_performance_test.go, functests/1_performance/topology_manager.go, functests/2_performance_update/updating_profile.go, functests/3_performance_status/status.go, functests/4_latency/latency.go, functests/utils/client/clients.go, functests/utils/mcps/mcps.go, functests/utils/profiles/profiles.go
Add explanation for Expect() failures when the expecations is not
obvious.
Note:
in general, we not change expectations like
```
Expect(err).NotTo(HaveOccurred())
```
because the ginkgo default behaviour is expressive enough.
We can use format strings freely in the gomega annotations. See:
https://onsi.github.io/gomega/ - "Annotating assertions"
=> tests: clarify failure reasons

tools/gather-sysinfo/gather-sysinfo.go
Explicitely collect this information from sysfs.
Another option is to check the processor flags: if "ht" is in there,
then SMT is enabled.
=> gather_sysinfo: collect SMT state from sysfs

pkg/profilecreator/profilecreator.go, pkg/profilecreator/profilecreator_test.go
As per the suggestions in the review of https://github.com/openshift-kni/performance-addon-operators/pull/566
we are refactoring the allocation logic to make it more readable by using
separate helper functions, one per allocation strategy
corresponding to splitReservedCPUsAcrossNUMA=false/true
=> Make the allocation logic more readable with helper functions

controllers/performanceprofile_controller.go, controllers/performanceprofile_controller_test.go, functests/0_config/config.go, functests/1_performance/performance.go, functests/utils/mcps/mcps.go, hack/wait-for-mcp.sh, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Currently, the operator generates a MachineConfig with the name of performance-<pao-name> and
does not follows a convention of pretending a numerical value to the name so when the rendered
version of the MCP is generated it is applied in whatever alphanumerical order it shows in the
list of oc get mc.
Now, when a cluster-admin wants to do further customizations, it cannot longer create MC with
a prepend index like 99-my-custom-mc-fix as it will not be applied correctly when the MCP is rendered.
Fixes #490
=> Generate a machine config name with the numerical prefix

functests/1_performance/cpu_management.go
Merge pull request #573 from cynepco3hahue/remove_psr_check_from_rcu_nocbs_test
Bug 1936953: remove the psr check from the rcu_nocbs test
(cherry picked from commit ea64a9f8f4716e27db08fcca3e2c38725569f695)
=> [release-4.7] remove the psr check from the rcu_nocbs test

cmd/performance-profile-creator/cmd/root.go, pkg/profilecreator/profilecreator.go, pkg/profilecreator/profilecreator_test.go
In this PR we:
- Refactor the code to move the code in RunE responsible for obtaining profile data from flags and creating the performance profile into private methods that are then called from RunE.
- Validate and populate Topology Manager Policy and  Real Time Kernel flag in performance profile as specified by the user.
- Populate Real Time Kernel flag in performance profile as specified by the user.
- Validate power-consumption-mode flag value provided by user.
- Ensure that reservedCPUCount is less than total number of CPUs.
=> Validate user specified arguments and populate fields in the created Performance Profile

hack/run-perf-profile-creator.sh
As we are no longer using shorthand in the PPC, this update in the
wrapper script ensures that it works without returning an error
=> Replace -M flag to --must-gather-dir-path in wrapper script

cmd/performance-profile-creator/README.md, cmd/performance-profile-creator/cmd/root.go, pkg/profilecreator/profilecreator.go, pkg/profilecreator/profilecreator_test.go
- based on the power mode specified by the user we populate the kernel arguments
in the additionalKernelArgs field of the created performance profile.
- Log  values of computed fields to explain how each field in the profile is populated.
- Minor refactoring to print logs corresponding to reservedCPUs
and isolatedCPUs just once after GetReservedAndIsolatedCPUs is
called.
- Additional unit tests for GetAdditionalKernelArgs
- Updates to the README
=> Populate the additionalKernelArgs field in the performance profile

must-gather/collection-scripts/gather_nodes
must-gather already depends on the perf-node-gather ds to detect
nodes on which it should collect data.
In turn, the daemonset doesn't explicitely select any node: we run, by
design, on each schedulable node, which, by default, exclude
control-plane nodes using NoSchedule taints.
On single-node deployment, the only prerequisite is that the node
must NOT have such a taint - which is a precondition to run any useful
workload anyway.
This PR hence just renames an internal variable for clarity; no changes
in logic are actually needed.
=> must-gather: rename variable for clarity

go.mod, go.sum, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/SNAPSHOT.md, vendor/github.com/jaypipes/ghw/alias.go, vendor/github.com/jaypipes/ghw/pkg/context/context.go, vendor/github.com/jaypipes/ghw/pkg/net/net.go, vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go, vendor/github.com/jaypipes/ghw/pkg/option/option.go, vendor/github.com/jaypipes/ghw/pkg/pci/address/address.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_net.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_pci.go, vendor/github.com/jaypipes/ghw/pkg/topology/topology.go, vendor/modules.txt
pull the last changes after 0.7.0, needed to properly capture PCI devices in snapshots and in general for better snapshot support.
SRIOV devices support still pending in the upstream project.
=> must-gather: ghw: update dependency

openshift-ci/Dockerfile.must-gather
We didn't update previously only because the 4.8 stream wasn't ready
back in time. Now we should switch to 4.8.
=> must-gather: align builder image to 4.8

build/assets/tuned/openshift-node-performance
The cost of using dynamic tuning (runtime=1) by the Tuned daemon is
currenty very high, and especially so in the OCP environment (see
rhbz#1921738).  PAO uses the Tuned scheduler plugin to set scheduling
policy and priority of ksoftirqd and rcuc kernel threads.  These are
per-CPU kernel threads which start very early during system boot and
exist with a unique PID regardless of CPUs being logically shutdown via
the sysfs interface.
It seems that the only reason for the dynamic scheduler configuration
(runtime=1) would be situations to pick up newly added NUMA
hot-pluggable hardware modules.  This unique case, however, very likely
does not justify the increased CPU utilization incurred by using dynamic
tuning by the Tuned scheduler plugin.
=> Turn off Tuned scheduler plugin dynamic tuning.

cmd/performance-profile-creator/cmd/root.go, pkg/profilecreator/profilecreator.go, pkg/profilecreator/profilecreator_test.go
1. Follow up from PR https://github.com/openshift-kni/performance-addon-operators/pull/575
2. Populate userLevelNetworking field in the performance profile
2. Enable disable-ht flag in PPC
3. Remove unused code and log system info to improve user experience
=> Enable disable-ht flag and user-level-networking in PPC

cmd/performance-profile-creator/cmd/root.go, pkg/profilecreator/mcp.go, pkg/profilecreator/profilecreator_test.go
Find the unique MCP labels, if more than one found prefer
the one including the mcp-name, pick a random one otherwise.
Refuse to create the profile if no unique label exists.
=> profile-creator: Always add the MCP selector to the profile

functests-extended/1_performance_operator_upgrade/upgrade_operator.go
Change the subscription installPlanApproval to Automatic before performing the upgrade in upgrade tests 
This is aligned according to: 
https://github.com/openshift/release/pull/17180/files#diff-2097e214d414ba4929d4246083e57002c2a97267650c44db7807ce425e8a289cR103
=> Change upgrade test installPlanApproval to Automatic

must-gather/collection-scripts/gather_nodes
fix warning when connecting to the podresources socket,
and fix redirection to be able to troubleshoot collection failures.
=> must-gather: fix warnings

openshift-ci/Dockerfile.tools
See https://docs.docker.com/engine/reference/builder/#env for details
no intended changes on behaviour
Spawned-from: https://github.com/openshift-kni/debug-tools/pull/22
=> Dockerfile: use modern ENV syntax

pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go
The net field under a profile can now pass to tuned specific net devices according to  interfaceName,device and vendor IDs.
Internal change - pass values as a udev regex that tuned supports.
=> Netqueues support for vendor and model

api/v2/performanceprofile_types.go, config/crd/bases/performance.openshift.io_performanceprofiles.yaml, deploy/olm-catalog/performance-addon-operator/4.8.0/performance.openshift.io_performanceprofiles_crd.yaml, docs/performance_profile.md
Spec.net field names changes:
vendor => vendorId
device => deviceId
=> Change net api fields to more logical names

config/rbac/role.yaml, controllers/performanceprofile_controller.go, deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
This update removes permissions that are not related to PAO
=> Remove superfluous rbac permissions

build/assets/tuned/openshift-node-performance, pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go
Fix tuned generation:
- Change regex for interfaceName (INTERFACE_NAME=>INTERFACE)
- Remove redundant  regex wrapping  :  removed `r'....' ` since tuned can use the expression without directly having a python regex wrapper passed to it
- Remove default [net] from tuned when device list is passed by the performanceprofile
=> Fix net tuned generation

cluster-setup/base/performance/operator_namespace.yaml, config/manager/manager.yaml, deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.5.0/performance-addon-operator.v4.5.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml, must-gather/node-gather/daemonset.yaml, must-gather/node-gather/namespace.yaml
In support of the workload partitioning feature
(https://github.com/openshift/enhancements/pull/703), we need to add
annotations to all management pods and namespaces so they can be
properly identified and assigned to segregated management cores on
clusters configured to do so.
=> Add management workload annotations

cmd/performance-profile-creator/cmd/root.go, pkg/profilecreator/mcp.go
Refuse to create the profile if all the nodes targeted by the input MCP
are not schedulable. This is the case for the master MCPs in "normal" clusters.
=> profile-creator: do not consider MCPs targeting unschedulable nodes

build/assets/tuned/openshift-node-performance
https://bugzilla.redhat.com/show_bug.cgi?id=1912118 fix allows to re-enable stalld in PAO deafult tuned profile
=>  Bug 1947773:  Re-enable stalld

Makefile
In case the Performance Profile Creator functional tests are executed
without creating PPC binary, the PPC functional tests would fail. In
order to avoid that, we make it a prerequisite to create the binary
prior to executing the functional tests.
=> Ensure PPC binary is created before running PPC functional tests

cmd/performance-profile-creator/cmd/root.go, functests-performance-profile-creator/1_performance-profile_creator/ppc.go, testdata/ppc-expected-profiles/profile1.yaml, testdata/ppc-expected-profiles/profile2.json
Do not automatically add the net.userLevelNetworking field to the performance profile output
if the user does not specify the corresponding user-level-networking param.
Update the regression tests to check for both scenarios (param specified or not).
=> performance-creator: Don't add the 'userLevelNetworking' field by default

functests/3_performance_status/status.go, functests/utils/profiles/profiles.go
The test will create a TuneD object with a TuneD profile that doesn't exist.
Tuned daemon will fail to apply it, therefore it will get into a Degraded state which eventually should be reflected in PAO status.
In the end, we remove the bad Tuned object and wait for PAO status condition to be Available again.
=> E2E test for consume NTO's per-node Tuned profile application status

go.mod, go.sum, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/pkg/context/context.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_cache_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/clonetree_block.go, vendor/github.com/jaypipes/ghw/pkg/snapshot/pack.go, vendor/modules.txt
update to the tip of ghw main branch to pull in the latest fixes,
most notably to avoid to leak temporary directories when consuming
snapshots:
https://github.com/jaypipes/ghw/pull/236
https://github.com/jaypipes/ghw/pull/240
=> ghw: consume latest fixes

config/manager/manager.yaml, deploy/olm-catalog/performance-addon-operator/4.4.0/performance-addon-operator.v4.4.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.5.0/performance-addon-operator.v4.5.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml, must-gather/node-gather/daemonset.yaml
As per https://github.com/openshift/enhancements/pull/739, the workload
annotations names are changing.
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/hold
Hold until after openshift/kubernetes#632 is merged please
=> Rename workload annotations

build/assets/tuned/openshift-node-performance
This is a downport of #600   : fix allows to re-enable stalld in PAO deafult tuned profile
=> [release-4.6] Bug 1949027: Re-enable stalld

build/assets/tuned/openshift-node-performance
The stalld service has higher priority than ksoftirqd, rcub and rcuc that
can lead to the system freeze under the load pressure. To avoid it we should
raise the scheduler priority of these threads to be higher than the stalld service.
Cherry picked partially from https://github.com/openshift-kni/performance-addon-operators/pull/462
=>  Bug 1960386: [release 4.6] Update the tuned profile to set higher scheduler priority

Makefile, controllers/performanceprofile_controller.go, functests-render-command/1_render_command/render_suite_test.go, functests-render-command/1_render_command/render_test.go, go.mod, hack/run-render-command-functests.sh, main.go, pkg/cmd/render/render.go, pkg/controller/performanceprofile/components/manifestset/manifestset.go, testdata/render-expected-output/manual_kubeletconfig.yaml, testdata/render-expected-output/manual_machineconfig.yaml, testdata/render-expected-output/manual_runtimeclass.yaml, testdata/render-expected-output/manual_tuned.yaml, vendor/modules.txt
Render command gets performance-profile manifest as an input and based on the provided profile,
it creates manifests yaml of the corresponding CR's which should have been created by the profile.
=> Render Command for PAO

tools/gather-sysinfo/gather-sysinfo.go
This is helpful to check the load balancing state of the cpus.
=> gather_sysinfo: collect sched_domain flags

Makefile, functests-render-command/1_render_command/render_test.go, testdata/render-expected-output/manual_tuned.yaml
- render-command-tests should depend on dist
- set more clear error message in case test failed
- manual_tuned.yaml's data field should be present as single line
=> Fix e2e test for render cmd

deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml, hack/annotations.json
Currently, the OLM propagates to the deployment annotations specified under CSV metadata and not the one specified under the install deployment.
See BZ https://bugzilla.redhat.com/show_bug.cgi?id=1950047 for more details.
=> Mitigate the OLM problem to pass annotations to the deployment

deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml, tools/csv-processor/csv-processor.go
Add resource request to be sure that our operator pod will have buarstable QoS.
Add tolerations to be sure that our operator will not evict because of CPU or
memory consumptions peaks.
=> Bug 1957291: add resource request and toleration's to the operator

functests/0_config/config.go, functests/1_performance/cpu_management.go, functests/1_performance/hugepages.go, functests/1_performance/performance.go, functests/utils/cluster/cluster.go, functests/utils/mcps/mcps.go
should provide similar functionality as https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/59 , giving SNO clusters longer timeouts
=> Increase tests timeout for single node test environments

OWNERS_ALIASES
Reflect the active contributors in the OWNERS_ALIASES.
=> update the contributor groups

functests/1_performance/cpu_management.go
Improve the unhelpful error message
```
Expected
<int64>: 52
to equal
<int64>: 5
```
no other intended changes in behaviour
Related-To: https://bugzilla.redhat.com/1946588
=> functests: better error message on failure

build/assets/tuned/openshift-node-performance, config/rbac/role.yaml, controllers/performanceprofile_controller.go, controllers/performanceprofile_controller_test.go, deploy/olm-catalog/performance-addon-operator/4.7.4/performance-addon-operator.v4.7.4.clusterserviceversion.yaml, functests/1_performance/performance.go, go.mod, go.sum, main.go, pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go, vendor/github.com/hashicorp/go-version/CHANGELOG.md, vendor/github.com/hashicorp/go-version/LICENSE, vendor/github.com/hashicorp/go-version/README.md, vendor/github.com/hashicorp/go-version/constraint.go, vendor/github.com/hashicorp/go-version/go.mod, vendor/github.com/hashicorp/go-version/version.go, vendor/github.com/hashicorp/go-version/version_collection.go, vendor/modules.txt
stalld will be enabled by default only if the node
has a required kernel version where https://bugzilla.redhat.com/show_bug.cgi?id=1912118
and https://bugzilla.redhat.com/show_bug.cgi?id=1903302 where fixed.
The minimum kernel versions required for stalld if in oc 4.7 are
4.18.0-240.22.1.el8_3.x86_64
4.18.0-240.22.1.rt7.77.el8_3.x86_64
These kernel version are availble only from openshift 4.7.7 and above
=> [release 4.7] Enabled stalld only from a minimum openshift release

functests-render-command/1_render_command/render_suite_test.go, functests-render-command/1_render_command/render_test.go, go.mod, vendor/modules.txt
Error output will reflect the exact difference between the files.
Inspired by https://github.com/openshift-kni/debug-tools/pull/34/commits/5e264aafde413f0f247ac16155c52dad4888b1f7
=> Improve error output for render E2E test

functests-performance-profile-creator/1_performance-profile_creator/ppc.go, testdata/ppc-expected-profiles/profile3.json, testdata/ppc-expected-profiles/profile3.yaml, testdata/ppc-expected-profiles/profile4.json, testdata/ppc-expected-profiles/profile4.yaml, testdata/ppc-expected-profiles/profile5.json, testdata/ppc-expected-profiles/profile5.yaml
Add tests related Performance Profile creator scripts. 
1. Negative scenarios:  Add tests cases where wrong arguments are passed to ppc script
2.  Expand regression tests to include HT disabled. 
Code in these test cases has been written in collaboration with [Tinashe Chipomho](https://github.com/CloudGrimm)
=> Performance Profile creator tests

functests/utils/consts.go
This commit fix the node selector in discovery mode
environment variables:
```
CLEAN_PERFORMANCE_PROFILE=false
NODES_SELECTOR=node-role.kubernetes.io/master
ROLE_WORKER_CNF=master
DISCOVERY_MODE=true
```
error:
```
panic: runtime error: index out of range [1] with length 1
goroutine 1 [running]:
github.com/openshift-kni/performance-addon-operators/functests/utils.init.0()
/home/sscheink/Documents/GolangProjects/src/github.com/openshift-kni/cnf-features-deploy/vendor/github.com/openshift-kni/performance-addon-operators/functests/utils/consts.go:62 +0x76f
Debugger finished with the exit code 0
```
Signed-off-by: Sebastian Sch <sebassch@gmail.com>
=> Fix discovery mode tests on SNO

build/assets/configs/99-netdev-rps.rules, build/assets/scripts/low-latency-hooks.sh
Bug 1967317: Do not create systemd update-rps service for veth devices
(cherry picked from commit 33b9640cf1f780fa1c9d2bc441fe5ecbf340b39a)
=> [release-4.8] Bug 1975348: Do not create systemd update-rps service for veth devices

functests/1_performance/cpu_management.go
the `find` command may succeed and return empty output, this is
a completely legal and valid behaviour, and we need to handle
this behaviour in the test.
=> functests: handle empty `find` output

functests/utils/utils.go
Always print the `stderr` from the command execution to make it easier to debug things.
=> e2e: print stderr during the command execution

functests/utils/client/clients.go
Replace apiextensions.k8s.io/v1beta1 with v1 inorder to allow
openshift upgrades from 4.8 to 4.9 without the need to set the operator
bundle with a max openshift version boundery
Note: The change takes place under the func tests utility that might
not affect at all the upgrade procedure but this change is applied in
order to cover all potential upgrade issues.
=> [Release 4.8] Replace apiextensions v1beta1 with v1

functests/4_latency/latency.go
**Why this fix is needed:**
An issue was discovered during a local build of the cnf-test image that @shajmakh did.
She built the image from https://github.com/Tal-or/cnf-features-deploy/tree/ship_hwlatdetect_cyclictest and ran the latency test which failed with ```"testName variable has incorrect value..."```
a careful examination of the code shows that this check will always fail, IOW the condition will always be false and it will throw this message and exit the test. 
**How do we fix it**
Removing the faulty check. In the first place, this check was intended to verify some flow which eventually was not written at all.
=> Latency tests: remove a condition which is always false

deploy/metadata/performance-addon-operator/4.9.0/annotations.yaml, hack/generate-metadata.sh
Currently, pipeline will only look for the Label in the image (label under the dockerfile of the bundle)
to know what version should be added in each OCP OLM index image,
however, note that the official olm sdk tool ensure that it is in the annotation
which means that this information might be used for any other purpose in the future and then,
the operator bundle might not be processed accordingly if the dockerfile and annotations are not keep in sync.
=> add the OCP label index under metadata annotations

functests/1_performance/performance.go
Now that bugzilla 1858347 ,1903302 , 1912118 are closed, we can remove the skip from the initrafms and stalld tests again.
In addition ,following bugzillas 1960386 and 1905492 , now we have automated test that checks that stalld scheduling priority is higher than ksoftirq and rcu{c,b}.
=> e2e: Add stalld test and remove no longer needed skips

pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go, pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go, testdata/render-expected-output/manual_kubeletconfig.yaml
Set the memory manager policy to `Static` and reserve
the memory on the NUMA node 0. The amount of reserved memory
equals `kube-reserved + system-reserved + hard eviction threshold`.
**Note to reviewers:**
I will provide e2e tests under the separate PR once the rebase on top of k8s 1.22 done.
=> Enable the memory manager

functests/1_performance/cpu_management.go
From now, by default the CRI-O will drop infra containers and will leave
them only for some special use cases as pod with `ShareProcessNamespace`
parameter under it.
=> e2e: fix infra containers reserved CPUs test

functests/utils/nodes/nodes.go
Output from the `oc exec` sometimes returns the empty output, one of
tries to fix it, is to replace the exec command with the rsh one.
=> e2e: replace the oc exec with oc rsh

functests/4_latency/latency.go
Verify all maximum latency values and not only the first one.
Improve the reg expression logic to return correct result.
=> Bug 1986006: e2e: fix oslat test

functests/1_performance/performance.go
Following bugzilla 1858347 resolvation , we removed the skip from the initramfs test and modified the path inside the pod to use lsinitrd binary from root file system
=> e2e: Reactivate and fix initramfs test

functests/4_latency/latency.go
This update will disable irq load-balancing and cpu load-balancing for the latency test pod.
Disabling the load-balancing is required for eliminating additional workload on the pods` CPUs.
=> Bug 1986399: Latency tests: disable irq and cpu load balancing

README.md, functests/4_latency/latency.go
By having the new LATENCY_TEST_CPUS env variable, the user will be able to specify the amount of CPUs
that will be used by the pod which runs the latency tests.
The LATENCY_TEST_CPUS env variable is optional, the default value is the total amount of isolated CPUs minus one (this behavior is identical to the prior one).
=> Bug 1986410 Control CPUs amount under latency-test pod

Makefile, hack/build-latency-test-bin.sh
To test the testsuite, it's useful to have the e2e latency
test suite compiled as standalone binary.
=> build: add helper and rule to build the latency test

functests/4_latency/latency.go
In a goal to not cache the values of the environment variables, we replaced the removed init() and replaced its functionality with getters that are being called inside the main Describe
=> Latency test: Replace init() with getters

functests/1_performance/cpu_management.go, functests/1_performance/netqueues.go, functests/1_performance/performance.go, functests/utils/nodes/nodes.go, functests/utils/pods/pods.go
Some of the tests under our CI are failing because that pod exec returns an empty output.
We do not know the reason, but we can mitigate a problem by re-running the command on the pod again as a short-term solution.
=> e2e: wait for the pod output

functests/4_latency/latency.go
We need to pass latencyTestRuntime (which is originally the LATENCY_TEST_RUNTIME env variable) as an argument before running the latency test pod.
Without it the user won't be able to control for how long the test will run.
=> Bug:1992710 Latency tests: Pass latencyTestRuntime as an argument to the test

functests/1_performance/netqueues.go
We should not call to any `Expect` commands outside of `BeforeEach` or `It`, othwerwise
we will affect the ginkgo dry run under cnf-tests.
=> e2e: improve net queues setup logic

functests/1_performance/performance.go
RCU kernel threads are available only on real time kernel nodes.Adding a condition for that in code before checking rcu in the system.
=> e2e: Add RT kernel check before checking existence of rcu

functests/4_latency/latency.go, functests/5_latency_testing/latency_testing.go
1)Added new negative check that checks runtime as a number greatest than allowed 32bit integer
2)Fixed Skip regular expression
3)Search the executable output as a string instead of bytes avoiding Gomega truncated error.
=> Latency e2e: Add new negative test case and fix regex

functests/1_performance/performance.go
The test should compare priorities of processes stalld, ksoftirq and rcuc or rcub
=> e2e: Modify regex for searching rcu{c,b} processes

README.md, functests/4_latency/latency.go
By having the new LATENCY_TEST_CPUS env variable, the user will be able to specify the amount of CPUs
that will be used by the pod which runs the latency-tests.
The LATENCY_TEST_CPUS env variable is optional, the default value is the total amount of isolated CPUs minus one (this behavior is identical to the prior one).
=> [release-4.8] Bug 1989531: Control CPUs amount under latency-test pod

build/assets/tuned/openshift-node-performance, testdata/render-expected-output/manual_tuned.yaml
The tuned config parser doesn't really like inline comments
(see:
https://github.com/openshift/cluster-node-tuning-operator/pull/271)
We don't really need inline comments, we can thus trivially rearrange
the comments to convey the same information but keeping them on their
own line. No intended changes of behaviour.
=> tuned: remove inline comments

functests/4_latency/latency.go
The latency test is passing the delay value to the runner container
https://github.com/openshift-kni/cnf-features-deploy/blob/6285b110359a63ebd72fd46d2ab8c6a9d019fc37/cnf-tests/pod-utils/cyclictest-runner/main.go#L22
as plain integer. However flag.Duration needs a Duration format
for which unit is mandatory.
This patch adds the "s" suffix to "scale" the value to seconds.
=> Bug 2006675: Test delay needs units to be valid duration

functests/4_latency/latency.go, functests/5_latency_testing/latency_testing.go
1)In latency.go, Check if actual CPUs number for latency pod is as set in the environment variable
2)In latency_testing.go: -check if actual runtime of the latency tools are as set in the environment variable  -Add new test case for oslat to check skipping the test incase there is less than 2 cpus
=> Latency e2e: Check actual CPUs number and runtime

functests/4_latency/latency.go
Reverts openshift-kni/performance-addon-operators#736
Agreed to keep the parameter as an Int instead of Duration in order to keep the backward compatibility of oslat tool which is using Int as well.
After this PR will get merged, we'll need to change cyclictest and hwlatdetect runners to accept Int instead of Duration type.
=> Revert "Bug 2006675: Test delay needs units to be valid duration"

.drone.yml
This reverts commit 2c70aa9276442a44597ec7719028ecf6b60926e1.
Turns out the removal PR was merged too hastily, and we want to keep drone.io integration.
=> Revert "drone.io: remove"

Makefile, functests/5_latency_testing/5_latency_testing_suite_test.go, functests/utils/daemonset/daemonset.go, functests/utils/images/prepull.go, tools/imgpull-tool/imgpull-tool.go
In order to pre-pull container images on the worker nodes, we create bogus, extremely cheap daemonsets which pull the images as side effect in order to run.
We just sleep in these daemonsets, so they are as cheap as a container can be.
We run these daemonsets in the testing namespace, so, once the tests are all done, the daemonsets will be cleaned up explicitly; no explicit cleanup (albeit nice) is required.
Other alternatives are running jobs to pull images as side effects, but they don't seem to be much simpler than daemonsets.
Daemonsets need to be named explicitely from the caller, which must also ensure their name is unique. This is awkward, but automatic naming would make the code too complex for the task at hand: there is no immediate need, because the number of images we should …
=> tests: images prepull using daemonsets

functests/1_performance/netqueues.go
If discovery mode is enabled but no profile is installed the tests currently panic.
Here, we are forcing all the tests to skip if that happens, providing the reason.
This check was missing for the netqueues test suite
=> E2e tests: do not panic in discovery mode with no profile for netqueues suite

functests/4_latency/latency.go, functests/5_latency_testing/latency_testing.go, functests/utils/nodes/nodes.go
The machines on which CI runs have few cpus (1-2 typically) for cost/scalability reasons.
Our tests want to exclusively allocate 1 or more cpus, which is impossible or impractical.
Trying to run our tests in these machines will lead to false negatives.
To keep the lane reliable, we add a check for worker nodes to verify nodes have sufficient
cpu amount to run the tests. Should not be the case, we skip the test (instead of failing).
=> Latency e2e: Verify node has sufficient cpu

Makefile
Latency tests will fail if discovery mode is disabled and performance profile is not found on the cluster.
To allow proper latency testing, we add functests/0_config suit to ginkgo suits of the target functests-latency-testing, a suit that will handle creating the profile in case it doesn't exist or continue executing the tests directly if exists.
=> Makefile: modify suits for target functests-latency-testing

api/v2/performanceprofile_types.go, config/crd/bases/performance.openshift.io_performanceprofiles.yaml, deploy/olm-catalog/performance-addon-operator/4.10.0/performance.openshift.io_performanceprofiles_crd.yaml, docs/performance_profile.md
Set isolated and reserved to required CPU parameters in CRD
Bug 4.7: https://bugzilla.redhat.com/show_bug.cgi?id=1986681
Documentation fix
In performance_profile.yaml:
cpu:
isolated: "1-3"
##reserved: "0" <----       Remove reserved
Test of performanceProfile crashes in 4.7 
Besides that, must be compulsory in every Release after 4.7
=> Set isolated and required CPU parameter in CRD

openshift-ci/Dockerfile.tools
The build system is trying to download and compile the latest ginkgo
version, which is too new and doesn't work anymore with the golang
version we use
=> Pin ginkgo version in Dockerfile.tools

openshift-ci/Dockerfile.tools
This is needed in order to be able to use go get package@version
notation.
=> Enable go modules in Dockerfile.tools

controllers/performanceprofile_controller.go
Watching tuned profiles will allow us to quickly reflect the tuned profile
status under the performance profile.
=> controller: watch tuned profiles for changes under the status

controllers/performanceprofile_controller.go
The controller should react to changes under our own
KubeletConfig and restore it to the desired state.
=> controller: fix kubeletconfig predicates

build/assets/tuned/openshift-node-performance, testdata/render-expected-output/manual_tuned.yaml
tuned was updated to handle new kernels (5.13 and newer) 
see https://github.com/redhat-performance/tuned/pull/365
the new kernels moved some sched_ and numa_ knobs from
the sysctl to the debugfs, thus add and abstract these knobs under the
scheduler plugin. With help of this abstraction it will write
the tuning to the correct place according to the kernel used.
Example:
[scheduler]
sched_migration_cost_ns = 500000
Will work on the old kernel the same way as:
[sysctl]
kernel.sched_migration_cost_ns = 500000
all occurences of sched_ and numa_ knobs were added
under the [scheduler] section in the base tuned profile in PAO
Signed-off-by: Yanir Quinn <yquinn@redhat.com>
=> tuned base profile to support new scheduler nobs

Makefile
Sometimes make generate works incorrectly and generate garbage files due to old /build/_output files. 
Usually this happens when cherry picking and generating new files between releases. 
=> Add clean to make generate to avoid _output garbage issues

functests/5_latency_testing/latency_testing.go
Due to bugzilla 2006675, cyclictest & hwlatdetec fail with parsing error resulting in pipelines failure.
To avoid failing the pipelines caused by known bugs & up until it is fixed, skip executing these two test scenarios & run them only with oslat.
=> Latency tests: skip running open BZ scenarios

api/v2/performanceprofile_types.go, config/crd/bases/performance.openshift.io_performanceprofiles.yaml, deploy/olm-catalog/performance-addon-operator/4.8.0/performance.openshift.io_performanceprofiles_crd.yaml, docs/performance_profile.md
Set isolated and reserved to required CPU parameters in CRD
Bug 4.7: https://bugzilla.redhat.com/show_bug.cgi?id=1986681
Documentation fix
In performance_profile.yaml:
cpu:
isolated: "1-3"
##reserved: "0" <----       Remove reserved
Test of performanceProfile crashes in 4.7 
Besides that, must be compulsory in every Release after 4.7
=> Bug 2033292: [Release 4.8] Set isolated and required CPU parameter in CRD 

config/manager/manager.yaml, deploy/olm-catalog/performance-addon-operator/4.10.0/performance-addon-operator.v4.10.0.clusterserviceversion.yaml
In the Telco far edge use case, a cluster might have limited management bandwidth. Upgrading such a cluster is expected to be 
time-constrained (capped by a maintenance window), and will involve container image pre-caching on the node before the upgrade.
Image pre-caching solution for SNOs relies on the assumption, that workloads can use locally stored images without contacting a registry.  This is only possible if container image pull policy is set to "IfNotPresent".
Current PAO image pull policy is explicitly set to "Always", which impairs the benefits of pre-caching
While solves a particular problem for SNO, this solution does not affect upgrades of any other deployment configuration in a negative way. Since all operator images are referenced by sha256 digest, any image update will …
=> Bug 2021202: Enable PAO image precaching

README.md, functests/4_latency/latency.go
By having the new LATENCY_TEST_CPUS env variable, the user will be able to specify the amount of CPUs
that will be used by the pod which runs the latency-tests.
The LATENCY_TEST_CPUS env variable is optional, the default value is the total amount of isolated CPUs minus one (this behavior is identical to the prior one).
=> [release-4.7] Bug 1989536: Control CPUs amount under latency-test pod

functests/1_performance/cpu_management.go
Added missing TCs ids so that their results will be reported to Polarion automatically.
=> e2e: Add missing TCs IDs

Makefile, hack/show-cluster-version.sh
For debug purposes, to doublcheck the reported cluster version
=> hack: show cluster version before to run functests

functests/1_performance/cpu_management.go, functests/utils/nodes/nodes.go, functests/utils/pods/pods.go, pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig.go, pkg/controller/performanceprofile/components/kubeletconfig/kubeletconfig_test.go, testdata/render-expected-output/manual_kubeletconfig.yaml
When we require the strictest NUMA alignment, we also enable the cpumanager policy option to require full physical cores only,
a feature available in kube >= 1.23.
Reprises https://github.com/openshift-kni/performance-addon-operators/pull/790
=> enable cpumanager policy options - full-pcpus-only

functests/1_performance/netqueues.go, functests/utils/nodes/nodes.go
Netqueues tests where previously done by taking a random device from all nodes then applying cross checks against nodes that do not necessarily contain the device.
An example for that could be a cluster where there are both virtual and bare metal worker nodes. 
The fix maps devices to nodes so the tests could check and match the right settings.
=> Bug 2046463: Switch to node-device nested maps for netqueues tests

build/assets/assets.go, controllers/performanceprofile_controller.go, controllers/performanceprofile_controller_test.go, functests/1_performance/performance.go, main.go, openshift-ci/Dockerfile.deploy, pkg/cmd/render/render.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go, pkg/controller/performanceprofile/components/manifestset/manifestset.go, pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go
Instead of copying assets under the operator image and loading them during the run, we can embed them during the compilation.
The PR should improve a number of things:
- caching of files, the code will not need to read files from the filesystem for every reconcile loop.
- vendoring performance-addon-operator under the NTO. We do not need to change the NTO image to include PAO assets.
/hold wait for 4.10 branching
=> Embed assets under the go compiled code

functests/4_latency/latency.go, functests/5_latency_testing/latency_testing.go
Missing fmt.Sprintf in the skip message leads to outputting the conversion character %d instead of minCpuAmountForOslat actual value.
Fix the message formatting by outputting fmt.Sprintf value and validate that in Latency_testing.go.
=> Latency e2e: fix skipping report when cpus amount is less than minimum

functests/1_performance/netqueues.go, functests/utils/nodes/nodes.go
Netqueues tests where previously done by taking a random device from all nodes then applying cross checks against nodes that do not necessarily contain the device.
An example for that could be a cluster where there are both virtual and bare metal worker nodes.
The fix maps devices to nodes so the tests could check and match the right settings.
=> [release-4.10] Bug 2050105: Switch to node-device nested maps

functests/4_latency/latency.go
Quota accounting takes resources and cause throttling which in turns casue latency, hence, we want to disabling it.
=> Bug 2061676: latency tests: disable cpu cfs quota

functests/2_performance_update/kubelet.go, functests/2_performance_update/updating_profile.go
- use patch instead of update to prevent resource update conflicts
- restore correct node labels
=> e2e: stabilize performance update tests

functests/utils/images/images.go
Cnf-tests image is used in latency test, update the image to 4.10 version.
=> Images: adjust cnf-tests image to 4.10

functests/5_latency_testing/latency_testing.go
Due to modification done in #830, tests requesting an odd number of CPU are failing due to rejecting the pod from running with SMTAlignmentError.
Adjust the tests to use an even number of CPUs.
And now that BZ 200667 is resolved, enable the tests that set LATENCY_TEST_DELAY to a non-zero value for cyclictest and hwlatdetect.
=> Latency testing: stabilize tests 

functests/1_performance/cpu_management.go
Add missing test id to enable results to be reported and stored properly.
=> [release-4.9] e2e: Add test ID

api/v2/performanceprofile_types.go, config/crd/bases/performance.openshift.io_performanceprofiles.yaml, deploy/olm-catalog/performance-addon-operator/4.7.4/performance.openshift.io_performanceprofiles_crd.yaml, docs/performance_profile.md, go.sum
cherry picking from: https://github.com/openshift-kni/performance-addon-operators/pull/792
Description
Set isolated and reserved to required CPU parameters in CRD
Bug 4.7: https://bugzilla.redhat.com/show_bug.cgi?id=1986681
Type of change
Documentation fix
Testing steps
In performance_profile.yaml:
cpu:
isolated: "1-3"
##reserved: "0" <---- Remove reserved
Test of performanceProfile crashes in 4.7
Besides that, must be compulsory in every Release after 4.7
=> Bug 2034146: [Release 4.7] Required cpu isolated and reserved BZ2034146

functests/1_performance/performance.go
Add the missing test id in order to properly update test run results.
=> e2e: add missing test_id

functests/4_latency/latency.go, functests/5_latency_testing/latency_testing.go
Following https://github.com/openshift-kni/performance-addon-operators/pull/889, running a latency tool test with no CPUs specified is currently panicking on nil pointer of the performance profile as it was not initialized.
Initialize the PP before checking if to skip the test due to odd CPU number.
=> e2e: Latency: initialize PP to avoid nil pointer 

hack/unittests.sh, tools/gather-sysinfo/gather-sysinfo_suite_test.go, tools/gather-sysinfo/gather-sysinfo_test.go
Add unit test of gather-sysinfo
gather-sysinfo is must-gather main tool
=> must-gather gather-sysinfo unit tests

must-gather/collection-scripts/gather_nodes
Some intensive CPU workload could be negatively affected by the
interruption of ISRs.
We would like to check that IRQ affinities are properly configured to
avoid problems.
That means no exclusively assigned CPU is listed in any IRQ affinity
list.
In kubernetes version >= 1.23 PodResourcesAPI provides us with the
exclusively assigned CPU for each container but in previous versions it
gives us all the CPUs used by the container which in fact could be the
default cpuset.
So for kubernetes version < 1.23 we need extra information to get the
exclusively assigned CPUs.
That is the list of pods with `qosClass == Guaranteed` so we could then
look for the CPUs in the PodResourcesAPI.
As the way to calculate exclusively assigned CPUs for kubernetes version
< 1.23 also works for kubernetes versions …
=> [release-4.7] Gather pod information to check IRQ load balancing

functests/1_performance/cpu_management.go, functests/4_latency/latency.go, functests/5_latency_testing/latency_testing.go, functests/utils/images/prepull.go, functests/utils/pods/pods.go
- add the runtime to stabilize the pod-phase condition
- verify tool args 
- change ImagePullPolicy to default
- fail the test if CPUs number is less than 1
=> E2e latency fixes

go.mod, go.sum, must-gather/collection-scripts/gather_nodes, vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/podinfo.go, vendor/modules.txt
From v1.7 `debug-tools` has a new `podinfo` command to help us to gather
info from pods to complement PodResourcesAPI info.
The information gathered is the same that was gotten with the current
`oc` command.
=> Use new `podinfo` command to gather pod data

pkg/controller/performanceprofile/components/tuned/tuned_test.go
Due to some dependency update profile.spec.data field is now written as
a multiple lines string instead of as a single line string.
We are using regex **in tests** to check for some content in this field and these new
line feeds could make them fail so we have updated the regex to check
only the data we are interested on despite what could be in between.
See https://github.com/openshift-kni/performance-addon-operators/pull/911#discussion_r904649553
=> [release 4.8] Modify regex to reflect new "data"

Makefile, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/utils/hugepages/machineconfig.go, tools/hugepages-machineconfig-generator/hugepages-machineconfig-generator.go
There is a need to configure the OCP cluster with hugepages settings independently from PAO. Adding this utility supports generating new machine config with hugepages settings only.
=> tools: generate machine config with hugepages settings only

functests/5_latency_testing/5_latency_testing_suite_test.go, functests/5_latency_testing/latency_testing.go, functests/utils/profilesupdate/profile_update.go
Some tests in the suites require setting the number of CPUs to be used by the latency pod. If the available cpus is not sufficient, the tests will be skipped.
The goal of the suite is to verify that the main tests of the latency tools are executed as expected.
So to overcome this, update the isolated CPUs for this suite to CPU set that guarantees to execute the tests properly, and restore the initial set when finished.
=> e2e: latency: Update PP isolated cpus to match test requirement

.github/workflows/release-hp-mc-generator.yml
Add new workflow to build and release binary for tools/hugepages-machineconfig-generator to enable using it externally.
=> gh actions: add workflow to build tool

must-gather/collection-scripts/gather_nodes, must-gather/node-gather/clusterrole.yaml, must-gather/node-gather/clusterrolebinding.yaml
podinfo command need to list all pods in all namespaces scheduled to a
certain node. In order to do that it needs to have the proper
permissions.
Add a new ClusterRole,adding read permisions over pods in all namespaces,
and a ClusterRoleBinding to bind those persmissions to the
ServiceAccount used by the must-gather daemonset pods.
podinfo in pao: #907 
podinfo command: openshift-kni/debug-tools#64
=> must-gather:podinfo: Add RBAC elements to list pods

functests/5_latency_testing/5_latency_testing_suite_test.go, functests/5_latency_testing/latency_testing.go, hack/run-functests.sh
The tests in 5_latency_testing should run only on-demand and by using different make target with relevant dependencies. Skip this package using ginkgo skipPackage flag.
additionally to some cleanup and fixes, see commits for more details.
=> hack: skip tests under 5_latency_testing

must-gather/collection-scripts/gather_nro, must-gather/collection-scripts/namespace
must-gather is trying to get NRO related information (CRDs, and
namespaced artifacts) no matter what and so, when NRO is not installed
in the cluster some nasty error messages appear because those elements
are not found.
These are not errors but to avoid missleading the users it is better to
avoid them by not gathering the NRO information if we cannot detect the
NRO namespace.
A small message appears in console in this case.
=> must-gather: numaresources: Avoid error messages when NRO is not installed

functests/utils/profiles/profiles.go
UpdateWithRetry wants to get a fresh copy of the profile
to update to avoid conflicts; because of a copy/paste
mistake, it was trying to reapply the original profile,
not the updated copy, thus defeating the purpose of the function.
=> utils: use updated profile, not original

functests/1_performance/performance.go
Add missing test id to the test case that verifies that imagePullPolicy of the operator pod is ifNotPresent, this will enable clear test result reporting.
=> Add test_id to imagePullPolicy should be ifNotPresent tc

must-gather/collection-scripts/gather_nodes, openshift-ci/Dockerfile.must-gather
Add ethtool -k and ethtool -l to must gather collected data
Save in ethtool_features and ethtool_channels files
=> Add ethtool -k and ethtool -l to must gather collected data

functests/5_latency_testing/latency_testing.go
lately some of the latency tests were failing and it turned out that the failure is due to that the maximum latency found was greater than anticipated. The tests in this suite do not care about the measured latency because we do not care to tune the systems in the first place. Its only goal is to run the tests of the latency tools with different values of environment variables and validate that the tool actually runs with these parameters.
Increase the maximum latency threshold so that the test doesn't fail in case of a high latency result.
=> e2e: latency testing: increase the expected threshold and fix gomega truncating output
