OWNERS_ALIASES
Signed-off-by: Marc Sluiter <msluiter@redhat.com>
=> Added Yanir to approvers

openshift-ci/Dockerfile.tools
Signed-off-by: David Vossel <davidvossel@gmail.com>
=> updates to prow build root container

cmd/manager/main.go
There are two options for the leader election. The SDK defaults to the simpler one ("Leader for life") which trades off slower failover (5 minutes by default - the pod-eviction-timeout) for a guarantee that there can never be two leaders. The other one (used here) fails over faster, but there may be two leaders if one node is running a clock 50% faster(!) than the others unless you tweak the default timeouts to accommodate the clock skew rate you expect.
The controller-runtime library provides a way to set leader among pods via config map annotation, that includes leader lease. In case when the pod fails to update the lease under the config map, the other pod will acquire the leader.
Otherwise, the operator-SDK do not provide the lease feature and just creates the
config map, so until the …
=> Use leader election mechanism from controller-runtime library

pkg/controller/performanceprofile/performanceprofile_controller.go, pkg/controller/performanceprofile/performanceprofile_controller_test.go
=> Add events to the performance profile controller

hack/wait-for-mcp.sh
echo the number of retries left while waiting for MCP to be updated.
=> Echo retries left

Makefile
Reverts openshift-kni/performance-addon-operators#75
We don't want to have binaries in our repo, and we will find a better solution.
=> Revert "operator-sdk: "vendor" the executable"

hack/clean-deploy.sh
Improved cleanup script
Successfully tested on my cluster
@gsr-shanks fyi
=> Improved cleanup script

cluster-setup/base/performance/performance_profile.yaml
reserved cpu should be equal to nonIsolated cpu
=> Fix the number of reserved CPUs

build/assets/scripts/pre-boot-tuning.sh
**What was the problem**
Pre boot tuning checked if the custom initrd image was applied on all of the bootloader entries instead of only checking the current(latest) version.
**Fix**
Pre boot tuning was fixed to check if the latest boot-loader entry has the custom initrd image.
Applying new entries was adjust as well to match the current entry file.
=> Fix pre-boot tuning to check latest boot entry

cluster-setup/base/performance/performance_profile.yaml, cluster-setup/ci-cluster/performance/performance_profile.patch.yaml, deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml
=> Move environment specific parameters from the base yaml

openshift-ci/Dockerfile.tools
=> Explicitly set HOME env variable

pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
**What is the Probelm?**
When cpu.reserved field is missing in perfomance profile, a nil panic will occur:
`bserved a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)`
**What was fixed**
Added a nil check before creating ignition content for pre boot tuning that relies on cpu.reserved value
**Note**
Another way to ensure proper behaviour here is to validate that the field exists if its defined as a mandatory field
=> Add nil check before creating preboot ignition

openshift-ci/Dockerfile.registry.build
Signed-off-by: Marc Sluiter <msluiter@redhat.com>
=> Revert CI registry URL

build/assets/scripts/pre-boot-tuning.sh, build/assets/scripts/reboot.sh, functests/performance/performance.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
Reverts openshift-kni/performance-addon-operators#120
=> Revert "[release-4.4] Reboot from rpm-ostree injection in pre-boot"

build/assets/scripts/pre-boot-tuning.sh, build/assets/scripts/reboot.sh, functests/performance/performance.go, hack/wait-for-mcp.sh, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
We had some trouble on release-4.4 which we fixed directly on the release branch.
This should not get best practice, however it most the most effective way to move forward.
With this PR we align master with changed from the release branch.
Changes are:
- timeout commit of #126 
- #130: revert of #120, which was #104 on master
- #131: partial re-apply of #120 / #104
=> Sync with release-4.4

cluster-setup/ci-cluster/performance/performance_profile.patch.yaml
Reason: https://bugzilla.redhat.com/show_bug.cgi?id=1811630
=> Temporarily disable RT kernel

cluster-setup/ci-cluster/performance/performance_profile.patch.yaml, deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml, deploy/crds/performance.openshift.io_v1alpha1_performanceprofile_cr.yaml, deploy/olm-catalog/performance-addon-operator/0.0.1/performance-addon-operator.v0.0.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/0.0.1/performance.openshift.io_performanceprofiles_crd.yaml, functests/performance/performance.go, pkg/apis/performance/v1alpha1/performanceprofile_types.go, pkg/apis/performance/v1alpha1/zz_generated.deepcopy.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig_test.go
=> [release-4.4] Add additional kerenel arguments option in CRD

build/assets/scripts/hugepages-allocation.sh
=> Add verification to the hugepages allocation script

functests/performance/topology_manager.go
This PR slightly improves the logic of topology manager functional test - now it should work with any pre-configured topology manager policies
=> make topology manager func test more flexible

functests/performance/updating_profile.go
Running this test leads to reconfiguring performance profile parameters, as result some other functional tests might be failed. That's why we decided to run such kind of tests when other will be completed:
https://github.com/openshift-kni/performance-addon-operators/blob/cf3e15b602ce3f015c2e432bb1c8ebf2eff00606/hack/run-functests.sh#L10-L11
and it works fine for CI, because cluster is killed at the end and we don't care about latest profile values on it. 
But it is not good for real customer who want to keep his cluster after running this test (he needs to revert back all changes to get initial tuning parameters)
=> add functional test: changing nodeSelector in performance profile

functests/performance/updating_profile.go, hack/run-functests.sh
=> [release-4.4] Add functional tests - updating performance profile

hack/clean-deploy.sh
This PR modifies clean-deploy.sh script. It removes node label and mcp based on nodeSelector field in performance profile
=> clean-deploy.sh gets labels and mcp from performanceprofile settings

functests/test_suite_test.go, go.mod, go.sum, vendor/kubevirt.io/qe-tools/LICENSE, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/junit_reporter.go, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go, vendor/kubevirt.io/qe-tools/pkg/polarion-xml/polarion_xml.go, vendor/modules.txt
=> [release-4.4] Add Polarion reporter

CONTRIBUTING.md, Makefile, README.md, docs/performance_profile.md, docs/troubleshooting.md, hack/docs-generate.sh, tools/docs-generator/docs-generator.go
- extended README.md
- cleanup of CONTRIBUTING.md
- added performance_profile.md (it is generated from the struct comments)
- added troubleshooting.md
=> Improved docs

openshift-ci/Dockerfile.registry.build
=> [release-4.4] Backport CI registry URL fix

go.mod, go.sum, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/README.md, vendor/kubevirt.io/qe-tools/pkg/ginkgo-reporters/polarion_reporter.go, vendor/modules.txt
=> [release-4.4] Updating qe-tools to v0.1.6

hack/clean-deploy.sh, hack/wait-for-mcp.sh, openshift-ci/Dockerfile.registry.build
no comment...
edit: also fixed oc wait
=> Change CI registry URL and fix oc wait

functests/performance/updating_profile.go
This is a fix for error:
_Operation cannot be fulfilled on performanceprofiles.performance.openshift.io \"performance\": the object has been modified;_
Either we need to get latest "profile" before running Update() or we can use Patch() for it. 
Decided to go with Patch()
=> Fix for nodeSelector test

functests/performance/updating_profile.go
Tests in updating_profile.go make big changes in profile, so we need to restore them back for right functionality of the cluster
=> Restore performance profile parameters after running tests

tools/csv-generator/csv-generator.go
Allow the generator-tool to optionally read the full description
from a separate text file instead of hardcoding it.
The content of the file will be copied verbatim in the
`csv.Spec.Description` field.
=> csv-generator: add option to read description

functests/performance/cpu_management.go, functests/performance/hugepages.go, functests/performance/performance.go, functests/performance/topology_manager.go, functests/utils/nodes/nodes.go, functests/utils/pods/pods.go, functests/utils/utils.go
Refactored all execs to use the new `ExecAndLogCommand()` func, and cleaned up some related code.
=> Better logs for command executions

functests/2_performance_update/updating_profile.go
In this PR I wanted to combine nodeSelector and label removing tests. First of all, it will save us from one additional MCP update during cleaning leftovers. And second - I don't think it's good idea to remove worker-rt label in tests (at the end we can get cluster without any worker-rt nodes, so any follow-up tests will be failed). If we are want to return all cluster stuff back to initial state after running our tests - it's better to "play" with worker-test label and skip this test if we don't have it.
=>  Removing leftovers after running nodeSelector and label removing tests

functests/2_performance_update/updating_profile.go
This test ensures that RT Kernel is not installed when the
realTimeKernel field does not exist in performance profile
=> RT Kernel is not installed when PerformanceProfile has no realTimeKernel field

functests/utils/client/clients.go, functests/utils/mcps/mcps.go
Getting the MCP might fail especially when waiting for Updated condition during config when master nodes are rebooted, so retry it a few times.
=> Retry getting MCP

cluster-setup/manual-cluster/performance/performance_profile.yaml, hack/clean-deploy.sh
added nodeSelector to manual profile
updated cleaning script - now it should go thru all existing profiles and clean cluster accordingly
=> Fix for manual profile and cleaning script

functests/1_performance/topology_manager.go, functests/utils/nodes/nodes.go
This tests already covered with the integration tests - https://github.com/openshift-kni/cnf-features-deploy/blob/a44fb31b357fbcf2c1a6a9b1cfb10bbf39c490c9/functests/dpdk/dpdk.go#L161
=> Delete SR-IOV test

functests/0_config/config.go
Waiting for it to be "updating" is needed because of the latency between when we create the profile
and the time when it start updating. If the profile is already there, that latency is likely
to be already paid, so we can wait directly for updated.
The drawback is that if the pool is already updated (i.e. on two sequent test run), the config will
timeout because the pool will never reach updating.
=> Don't wait for mcp to be updating if the performance profile was created previously

docs/releasing.md
Added release branches, re-ordered some paragraphs, and smaller fixes
=> Improved release doc.

Makefile
Signed-off-by: Marc Sluiter <msluiter@redhat.com>
=> [release-4.5] Update default tag

hack/clean-deploy.sh
clean-deploy.sh does not delete all necessary resources after merging  PR #203
=>  Fix names in clean-deploy.sh script

hack/deploy.sh
This reverts commit ded2aab5
/cherrypick release-4.5
=> Revert "Workaround oc behaviour change after rebase on k8s 1.18"

functests/0_config/config.go
In case of a manifest being there, we use it for tests.
This should cover the case of dpdk not requiring a new profile.
=> Make it possible to override the performance profile used in tests.

Makefile, cluster-setup/base/performance/operator_subscription.yaml, cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml, deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml, functests-extended/1_performance_operator_upgrade/test_suite_performance_operator_upgrade_test.go, functests-extended/1_performance_operator_upgrade/upgrade_operator.go, hack/csv-generate.sh, hack/run-upgrade-tests.sh
and updated operator update test to run from 4.5. to 4.6
=> Added 4.6 channel

hack/clean-deploy.sh
previously it deleted only first value in $mcps array
=> fix for cleaning script

deploy/crds/performance.openshift.io_performanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operator/4.6.0/performance.openshift.io_performanceprofiles_crd.yaml, docs/performance_profile.md, pkg/apis/performance/v1alpha1/performanceprofile_types.go
Fixes minor typos in comments and documentation.
Fixes #280
=> Fixes minor typos in comments and documentation

functests/performance/cpu_management.go, functests/performance/updating_profile.go
=> [release-4.4] kubelet.conf has some nicer formatting now on the nodes

Makefile
Fix and document the dependencies/priorities between the
`registry-container` and the `bundle-container` targets.
=> makefile: fix target interdependencies

README.md
=> README: document manifests tree generation

functests/2_performance_update/updating_profile.go
https://bugzilla.redhat.com/show_bug.cgi?id=1854245
=> Verify irqbalance tuning is reverted

docs/cpu-load-balancing.md
=> Provide documentation for the disabling CPU load balancing feature

functests/1_performance/rt-kernel.go, functests/2_performance_update/updating_profile.go, functests/utils/nodes/nodes.go
Improve the PREEMPT RT check, to avoid situation when the kernel version
will have unexpected changes, like the recent change from `PREEMPT RT` to
`PREEMPT_RT`.
The change occured under the kernel version:
```
Linux test-66vhx 4.18.0-211.rt5.23.el8.x86_64 #1 SMP PREEMPT_RT Thu Jun 4 13:01:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
The change includes:
- check if the node booted with the RT kernel
- check if the RT kernel compiled with the `CONFIG_PREEMPT_RT=y`
=> Fix the RT kernel e2e test

README.md
Let's present the nice interaction diagram right in the README.
=> README: link nice interaction diagram

cluster-setup/manual-cluster/performance/performance_profile.yaml, functests/1_performance/hugepages.go, functests/2_performance_update/updating_profile.go
It verifies updating nodes with multiple hugepages sizes
=> Improvement for hugepages update test

pkg/controller/performanceprofile/components/profile/profile.go, pkg/controller/performanceprofile/components/profile/profile_test.go
It can mislead what the exact configuration the node will have
when a user will specify duplication entries for the same size
of hugepages. To avoid it the controller will raise a validation
error.
Examples of problematic configuraitons:
```yaml
pages:
- count: 1
node: 0
size: 1G
- count: 2
node: 0
size: 1G
```
```yaml
pages:
- count: 1
size: 1G
- count: 2
size: 1G
```
=> Add validation to prevent hugepages duplication

functests/1_performance/cpu_management.go
Also added some fixes for cpu affinity test
=> Added test that verifies rcu_nocbs kernel argument on the node

functests/4_latency/latency.go
This will add steps for better both code & test readability
=> Adding readability for the latency test

cluster-setup/base/performance/operator_subscription.yaml, cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml, deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.5.1/performance.openshift.io_performanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml, hack/csv-generate.sh, hack/run-upgrade-tests.sh
=> release-4.5: prepare CSV for 4.5.1 z-stream release

README.md, cluster-setup/base/performance/operator_subscription.yaml, cluster-setup/upgrade-test-cluster/performance/operator_subscription.patch.yaml, deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml, hack/csv-generate.sh, hack/run-upgrade-tests.sh
=> Update CSV and package

deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml
=> Update package yaml to point to 4.4.1 CSV

go.mod, go.sum
=> Remove bitbucket.org/ww/goautoneg dependency

go.mod, go.sum
=> [release-4.5] Remove bitbucket.org/ww/goautoneg dependency

openshift-ci/Dockerfile.registry.build
=> Change the registry

deploy/metadata/performance-addon-operator/4.6.0/annotations.yaml
=> Update the metadata with 4.6 channel

OWNERS_ALIASES
Remove inactive team members, and add new ones.
=> Update owners aliases

deploy/olm-catalog/performance-addon-operator/4.5.1/performance-addon-operator.v4.5.1.clusterserviceversion.yaml
=> Point 4.5 CSVs to the 4.5-snapshot

deploy/olm-catalog/performance-addon-operator/4.6.0/performance-addon-operator.v4.6.0.clusterserviceversion.yaml
add more annotations to our CSV
=> csv: add more annotations

functests/3_performance_status/status.go
For some reason old approach with changing currentConfig does not work -
sometimes it takes more than 30 minuted for MCP to update the status to
"Degraded"
MCO team adviced to rewrite the test - put the node/mcp to degraded state
by creating bad machineConfig.
=> Fix for test - MCP status in performance profile

README.md
=> Fix typo, and x.y / y.z discrepancies in README.md

README.md, docs/api-versions.md
v2:
- Added a Q&A section
Describe the relation between the Performance Addon Operator
and the v1,v1alpha1 Performance Profile APIs.
=> docs: Add API versions support doc

openshift-ci/Dockerfile.index-gen.ci, openshift-ci/Dockerfile.index.ci
=> Provide the Dockerfile to generate index database under the CI

functests/1_performance/hugepages.go
Making test more robust. Currently it fails on the cluster with several numa nodes because
we compare the number of hugepages on one numa with total number of hugepages on the whole node.
=> Bug 1889633: Fix for test: hugepages with NUMA node

functests/1_performance/performance.go
- change the node selector for the second profile, just to avoid any missconfigurations
- wait for the v1alpha1Profile deletion
=> e2e: fix conversion test

cluster-setup/ci-upgrade-test-cluster/kustomization.yaml, cluster-setup/ci-upgrade-test-cluster/performance_profile.yaml, cluster-setup/mcp-only-cluster/kustomization.yaml, cluster-setup/mcp-only-cluster/machine_config_pool.yaml, deploy/metadata/performance-addon-operator/4.4.1/annotations.yaml, deploy/metadata/performance-addon-operator/4.5.1/annotations.yaml, deploy/olm-catalog/performance-addon-operator/4.4.1/performance-addon-operator.v4.4.1.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.4.1/performance.openshift.io_performanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml, hack/run-upgrade-tests.sh, openshift-ci/Dockerfile.bundle-4.4.ci, openshift-ci/Dockerfile.bundle.ci, openshift-ci/Dockerfile.registry.build, openshift-ci/Dockerfile.registry.upstream.dev, openshift-ci/Dockerfile.src.ci
=> [release-4.5] ci: adaptations to operator pipeline

openshift-ci/Dockerfile.index-gen.ci
=> [release-4.6] Provide dockerfile to generate index.db via opm

openshift-ci/Dockerfile.index.ci
=> Change the index database path to be in sync with CI expectations

pkg/controller/performanceprofile/components/utils.go, pkg/controller/performanceprofile/components/utils_test.go
We don't need these utilities anymore
=> utils: remove dead code

functests/1_performance/performance.go, pkg/controller/performanceprofile/components/machineconfig/machineconfig.go
Test the OCI configuration uses the correct RPS mask.
Test the RPS services uses the correct RPS mask.
Test all node network devices have the correct mask set.
Test all node pods network devices have the correct mask set.
No Polarion test id yet, approved by  @gsr-shanks
=> RPS E2E test

controllers/performanceprofile_controller.go, controllers/performanceprofile_controller_test.go, controllers/status.go
Promote kubelet config errors to the performance profile. It will promote only the failure error only when it the most recent condition.
=> Promote kubelet config errors

hack/run-upgrade-tests.sh
=> Fail the upgrade test when the cluster deploy failed

deploy/olm-catalog/performance-addon-operator/4.5.2/performance-addon-operator.v4.5.2.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.5.2/performance.openshift.io_performanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml, hack/csv-generate.sh
=> release-4.5: prepare CSV for 4.5.2 z-stream release

functests/1_performance/cpu_management.go, functests/2_performance_update/updating_profile.go, functests/utils/nodes/nodes.go
Also combined some duplicated code in cpu_management.go file
=> Add test verifying that IRQ balance can be disabled per POD

docs/irq-load-balancing.md
=> docs: Add a debugging section to the IRQ load balancing doc.

functests/1_performance/performance.go, functests/1_performance/rt-kernel.go
=> e2e: fix nil pointer errors during dereference of the enable field

functests/1_performance/cpu_management.go
1. Remove Duplicate Polarion id for test case: Verify CPU affinity mask, CPU reservation and CPU isolation on worker node
2. Add test Case id for Test case:  Check CPU Affinity and Isolation on Not-Guaranteed QoS class pod
=> Remove Duplicate Polarion test case id:

functests/utils/utils.go
=> e2e: timeout command execution after two minutes

deploy/olm-catalog/performance-addon-operator/4.7.0/performance-addon-operator.v4.7.0.clusterserviceversion.yaml, tools/csv-processor/csv-processor.go
=> Bug 1899411: include the API version under the CSV owned CRDs

functests/1_performance/performance.go
This PR improves the test in scenario when we have some additional Tuned based on PAO profile:
```
[test_id:28467][crit:high][vendor:cnf-qe@redhat.com][level:acceptance] Should contain configuration injected through the openshift-node-performance profile [It]
/home/dshchedr/job/cnf/sno/performance-addon-operators/functests/1_performance/performance.go:226
Timed out after 480.000s.
active_profile is not set to openshift-node-performance-performance. <nil>
Expected
<string>: openshift-configuration-hotfixes
to equal
<string>: openshift-node-performance-performance
``` 
This happens because the file /etc/tuned/active_profile on the node contains new Tuned name (openshift-configuration-hotfixes), but we are trying to compare it with name in Performance Profile
Small improvement in this PR …
=> Make test "tuned profile validation" more flexible

controllers/performanceprofile_controller.go, controllers/performanceprofile_controller_test.go, controllers/status.go
Our logic to watch for machine config pools icorrect, because
the machine config pools not owned by the performance profile.
To fix it our logic will watch all machine config pools and will map
it to the performance profile.
=> Bug 1903820: watch machine config pools not owned by the performance profile

functests/1_performance/performance.go
=> e2e: fix nil pointer under the conversion test

controllers/status.go
=> Revert the remove of duplicate MCP entries

build/assets/tuned/openshift-node-performance, pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go
Reverts openshift-kni/performance-addon-operators#481
=> Revert: does not set RT parameters for non-RT kernel

README.md
=> docs: Add a note about PAO supporting only AllNamespaces InstallModeType

build/assets/tuned/openshift-node-performance, pkg/controller/performanceprofile/components/tuned/tuned.go, pkg/controller/performanceprofile/components/tuned/tuned_test.go
Reverts openshift-kni/performance-addon-operators#482
=> Revert "Merge pull request #481 from cynepco3hahue/disable_rt_parameter"

deploy/metadata/performance-addon-operator/4.8.0/annotations.yaml, deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.8.0/performance.openshift.io_performanceprofiles_crd.yaml, openshift-ci/Dockerfile.bundle-4.7.ci
=> deploy: docker: prepare 4.8 manifests

must-gather/collection-scripts/gather_nodes, openshift-ci/Dockerfile.must-gather, tools/gather-sysinfo/gather-sysinfo.go
=> snapshot sysfs/procfs inside must-gather

openshift-ci/Dockerfile.deploy
=> Add performance-profile-creator binary to the PAO Dockerfile

cmd/performance-profile-creator/README.md
Documentation for the PRs:
1. https://github.com/openshift-kni/performance-addon-operators/pull/511
2. https://github.com/openshift-kni/performance-addon-operators/pull/513
3. https://github.com/openshift-kni/performance-addon-operators/pull/515
=> Performance Profile Creator Documentation

config/samples/kustomization.yaml, config/samples/performance_v1alpha1_performanceprofile.yaml, deploy/olm-catalog/performance-addon-operator/4.8.0/performance-addon-operator.v4.8.0.clusterserviceversion.yaml
Fixes the warning message during the CSV generation.
=> Provide v1alpha1 performance profile example under the CSV

Makefile, hack/bump-zversion.sh
=> hack: add helper to bump the zversion

openshift-ci/Dockerfile.index-gen.ci
=> Update the bundle used to generate index image

Makefile
=> Makefile: make sure the default target is "build"

build/assets/tuned/openshift-node-performance
=> Bug 1930107: Comment the stalld section to prevent stalld installation

deploy/metadata/performance-addon-operator/4.5.2/annotations.yaml, deploy/metadata/performance-addon-operator/4.5.3/annotations.yaml, deploy/olm-catalog/performance-addon-operator/4.5.3/performance-addon-operator.v4.5.3.clusterserviceversion.yaml, deploy/olm-catalog/performance-addon-operator/4.5.3/performance.openshift.io_performanceprofiles_crd.yaml, deploy/olm-catalog/performance-addon-operator/performance-addon-operator.package.yaml, hack/common.sh, hack/csv-generate.sh
=> release-4.5: prepare for 4.5.3 release

tools/gather-sysinfo/gather-sysinfo.go
Make sure we clone all the files ghw (not just gather_sysinfo) cares about.
=> must-gather: sysinfo: make sure we copy ghw files

functests/1_performance/cpu_management.go
We have flakiness during psr check, because:
1. OS creates rcuo process
2. rcuo process runs on some CPU
3. OS set the affinity for all rcuo processes
4. we are checking rcuo psr, but it did not run again so we will see psr before affinity change
It should be enough to check only the CPU affinity, because the assumption that the process can
not run on the CPU that the process does not pinned to it.
=> Bug 1936953: remove the psr check from the rcu_nocbs test

cmd/performance-profile-creator/cmd/root.go, pkg/profilecreator/profilecreator.go
Is not a server side component, is a cmd-line tool.
Look for errors early and come up with friendly user messages.
=> profile-creator: Friendlier error messages

OWNERS_ALIASES
=> Add myself under reviewers list

functests/1_performance/cpu_management.go
=> Bug 1947070: remove internal JIRA link from the IRQ load balancing test

go.sum, openshift-ci/Dockerfile.tools
=> Advance go version to 1.16.3

functests-extended/1_performance_operator_upgrade/upgrade_operator.go
This is a manual cherry-pick of https://github.com/openshift-kni/performance-addon-operators/pull/591
=> [release-4.5] Change upgrade test installPlanApproval to Automatic

api/v1/performanceprofile_types.go, config/crd/bases/performance.openshift.io_performanceprofiles.yaml, deploy/olm-catalog/performance-addon-operator/4.8.0/performance.openshift.io_performanceprofiles_crd.yaml
Rewrite the explanations about Isolated & Reserved CPU features to be more percise and accurate
=> Bug 1945010: Update CPU Section in PAO Doc

Makefile, functests-render-command/1_render_command/render_suite_test.go, functests-render-command/1_render_command/render_test.go
This PR makes sure we run the e2e render test in our CI flows.
=> e2e: hook in the render command e2e tests

functests/2_performance_update/updating_profile.go, functests/utils/nodes/nodes.go, functests/utils/utils.go, pkg/controller/performanceprofile/components/utils.go
Make the test more robust and with better logging to help understanding why we're getting failures lately.
=> E2E: irqbalance: improve the test output

docs/runtime-class.md
The documentation will explain what annotations you can use together with the performance profile runtime class.
=> Provide the runtime class documentation

openshift-ci/Dockerfile.bundle.upstream.dev
=> [release-4.6] Bump upstream bundle z-stream version

functests/2_performance_update/updating_profile.go, functests/utils/nodes/nodes.go
Backporting to 4.7 
1. functests/nodes: Add function to return numa nodes and associated cpus of the node  Add shared function GetNumaNodes which returns the number of numa nodes  and the associated cpus
2. Fix functests/2_performance/updating_profile: fix test to get  number of hugepages. Modify the test code to get the numa  nodes and then fetch fetch 1G and 2M hugepages per numa node..
=> [release-4.7] Fix code to test number of Hugepages per numa node

functests/1_performance/performance.go
=> e2e: provide correct timeout for tuned tests

functests/1_performance/performance.go
Improve status and error messages in the workqueue functest.
=> functests: improve messages

functests-performance-profile-creator/1_performance-profile_creator/ppc.go, functests/utils/utils.go
Add a new helper to make it easier and less complex to get
the stderr of a command execution.
=> functests: utils: add ExecAndLogCommandWithStderr

functests/1_performance/cpu_management.go
=> Bug 1947070: e2e: change skip message for IRQ load balancing test

README.md
=> Provide an example for the render command use

functests/4_latency/latency.go
Those tests will imitate the same behavior as oslat has.
It will create a pod, run the binaries test and check the latency results.
=> Add test for cyclictest and hwlatetect binaries under cnf-tests image

functests/1_performance/performance.go
automated 1972701 bug verification :check that stalld is running as FIFO with priority 10
=> automated 1972701 bug verification

cmd/performance-profile-creator/README.md
Also fixed missing space before "\"
=> Missing required cmd flags

functests/4_latency/latency.go
In the last update, setting the ```maximumLatency``` via the environment variables value was skipped (bug).
This update will set the values correctly.
Moreover, this update introduces a new unified environment variable for the maximum latency that will allow the user to use the same environment variable for all tests.
The specific environment variables will have precedence over this unified one.
=> Set maximumLatency variable

functests/1_performance/performance.go
Signed-off-by: Niranjan M.R <mrniranjan@redhat.com>
Add the Missing test case id for kernel argument managed_irq flag test case
=> Add test case id to kernel argument managed_irq flag test case

docs/irq-load-balancing.md
Fixes the broken link to the performance_profile.md file.
=> Broken link to the performance_profile.md

functests/1_performance/hugepages.go, functests/utils/nodes/nodes.go, functests/utils/pods/pods.go
=> e2e: use REST client to execute commands on the MCD pod

functests/1_performance/netqueues.go, functests/1_performance/performance.go, functests/utils/nodes/nodes.go
Signed-off-by: Niranjan M.R <mrniranjan@redhat.com>
=> e2e test  Automation for netqueues

functests/utils/profiles/profiles.go
We should get the updated version of the performance profile.
Otherwise, we will always try to update the profile with the old resource version
and will always get the conflict error.
=> e2e: fix profile UpdateWithRetry method

functests/4_latency/latency.go
Store the latency test log in unique file name with timestamp and when the test finishes print it to the console then remove it.
=> Bug 1990054: remove log file after test finishes

Makefile, functests/5_latency_testing/5_latency_testing_suite_test.go, functests/5_latency_testing/latency_testing.go, hack/run-latency-testing.sh
Automate the test plan for the latency tools.
The test plan consists of checking valid, invalid & default values of the environment variables for the latency tools tests.
=> Latency e2e: Add test cases in automation

api/performance_test.go, api/v2/performanceprofile_validation.go, api/v2/performanceprofile_validation_test.go, config/samples/performance_v2_performanceprofile.yaml, deploy/olm-catalog/performance-addon-operator/4.9.0/performance-addon-operator.v4.9.0.clusterserviceversion.yaml, hack/unittests.sh
=> unittest: fix validation and API tests

functests/4_latency/latency.go
Latency tests now display to the user a relevant error message about the invalid value that was set to the environment variable, along with the expected to be a valid value.
=> Latency e2e: Report relevant error message upon invalid values

deploy/metadata/performance-addon-operator/4.10.0/annotations.yaml
=> Add metadata for 4.10 bundle container

openshift-ci/Dockerfile.tools
This is needed for the forthcoming AcceleratedStartup PR
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
=> Add 'jq' to openshift-ci/Dockerfile.tools

functests/2_performance_update/updating_profile.go
Add two tests to verify:
-Uneven split of hugepages count between 2 numa nodes
-Even split of hugepages count between 2 numa nodes
=> e2e: Add TC to verify hugepages count on different NUMA nodes

functests/1_performance/performance.go
If workload partitioning is enabled on cluster, check `Resources.Requests["management.workload.openshift.io/cores"]`
instead of `Resources.Requests.CPU`
Same case for `Resources.Limits.CPU`
=> Update PAO resources regression test to account for workload partitioning

go.mod, openshift-ci/Dockerfile.tools
=> Update go version to 1.17.2

go.mod, go.sum, vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/podres.go, vendor/github.com/openshift-kni/debug-tools/pkg/knit/cmd/k8s/types.go, vendor/modules.txt
=> vendor: update debug-tools dependency

controllers/performanceprofile_controller.go
Watching tuned profiles will allow us to quickly reflect the tuned profile
status under the performance profile.
=> [release-4.8] Bug 2034179: controller: watch tuned profiles for changes under the status

functests/1_performance/performance.go
Fix to test case for BZ#2018443
=> Bug 2018443 - On a DU node deployed via ZTP process the performance-operator pod has limits set

controllers/performanceprofile_controller.go
=> controller: do not truncate original errors

functests-extended/1_performance_operator_upgrade/upgrade_operator.go
=> e2e upgrade: drop W/A for OLM bug

functests/1_performance/netqueues.go
This fix is aligned with 4.10 https://github.com/openshift-kni/performance-addon-operators/pull/837
and continues https://github.com/openshift-kni/performance-addon-operators/pull/831
=> fix netqueues device tests

functests/1_performance/netqueues.go
netqueues tests were adjusted with polling timers in order to allow
enough time for the tuned daemon and netqueues on the nodes
to be adjusted.
Signed-off-by: Yanir Quinn <yquinn@redhat.com>
=> Allow more update time for netqueues tests

functests/1_performance/netqueues.go
Skip from called functions will add an unwanted panic stacktrace that will litter the test logs.
Use Skip only from main test functions.
Signed-off-by: Yanir Quinn <yquinn@redhat.com>
=> e2e (netqueues): do not skip from called functions

controllers/performanceprofile_controller.go
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>
=> Remove ineffective if assignment on controller

functests/2_performance_update/kubelet.go
Signed-off-by: Niranjan M.R <mrniranjan@redhat.com>
=> BZ 1967911:  E2E Test cases for enabling unsafe sysctl in performance profile

OWNERS_ALIASES
=> update owners 20220421

OWNERS_ALIASES
Refresh the list of active contributors
=> update OWNERS 20220422

OWNERS_ALIASES
Refresh the list of active contributors
=> [release-4.6][manual] update OWNERS 20220422

README.md
Added deprecation message for PAO,PPC and render mode.
=> Deprecation header for main doc

tools/gather-sysinfo/gather-sysinfo.go
must-gather: Add offline cpus gather to collection nodes
=> must-gather: Add offline cpus gather

must-gather/collection-scripts/gather_nodes
=> must-gather: add dmesg data to must-gather

tools/gather-sysinfo/gather-sysinfo.go
This should have been done in #907 but was forgotten by mistake
=> Properly add new podinfo command to gather-sysinfo

must-gather/collection-scripts/gather_nodes
=> [release-4.9][manual] must-gather: add podinfo command leftover

functests/1_performance/performance.go
Automates https://bugzilla.redhat.com/show_bug.cgi?id=2055019
=> "Add imagePullPolicy verification test"

functests/2_performance_update/kubelet.go
Manual cherry-pick of NTO pr: https://github.com/openshift/cluster-node-tuning-operator/pull/394.
=> e2e: stabilize PAO update test

build/assets/tuned/openshift-node-performance, pkg/controller/performanceprofile/components/tuned/tuned_test.go, testdata/render-expected-output/manual_tuned.yaml
Backport of openshift/cluster-node-tuning-operator#510
=> [release-4.10] OCPBUGS-4165: Add ktimer to PAO tuned profile
